import type { Product, Demographic, DeliveryEstimate } from './types'

export const DELIVERY_ESTIMATES: Record<string, DeliveryEstimate> = {
  chattogram: {
    zone: 'chattogram',
    title: 'Chattogram Metro',
    eta: 'Same-Day / 24 Hours',
    costBDT: 100,
    costUSD: 1,
    freeThresholdBDT: 3000,
    freeThresholdUSD: 25,
    courier: 'Maison Chattogram White-Glove Fleet',
    description: 'Direct courier from our GEC Circle flagship atelier to your residence.',
  },
  dhaka_nationwide: {
    zone: 'dhaka_nationwide',
    title: 'Dhaka & 64 Districts',
    eta: '48–72 Hours',
    costBDT: 200,
    costUSD: 2,
    freeThresholdBDT: 5000,
    freeThresholdUSD: 45,
    courier: 'Domestic Priority Express Courier',
    description: 'Secured priority shipping with real-time SMS dispatch alerts.',
  },
  international: {
    zone: 'international',
    title: 'International (UK, USA, UAE, Global)',
    eta: '3–5 Business Days',
    costBDT: 3000,
    costUSD: 25,
    freeThresholdBDT: 30000,
    freeThresholdUSD: 250,
    courier: 'DHL Express Worldwide White-Glove',
    description: 'Customs-cleared door-to-door transit with luxury tamper-proof seal.',
  },
}

export const ATELIER_PRODUCTS: Product[] = [
  // ==========================================
  // WOMEN (3+ distinct luxury garments)
  // ==========================================
  {
    id: 'mulberry-silk-evening-gown',
    title: 'Mulberry Silk Draped Evening Gown',
    edition: 'Edition 01 • Haute Couture',
    category: 'Women',
    subcategory: 'Evening Gowns',
    silhouette: 'Fluid Draped',
    fabric: 'Pure Mulberry Silk',
    priceBDT: 18500,
    priceUSD: 155,
    vipPriceBDT: 15725,
    vipPriceUSD: 132,
    badge: 'Limited to 25 Pieces',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAtQRYe3HSpSkH6fBVb64n_uDA0AjbPTKuRCWAVzGZhjh6ST7Htod1UPInaOoDrHnng6ZToV0pDMnxa_33sSqsU3Uh8TilUr-rwcyd2rtTdSDn6LqcSXPNWSpQP1HiylMohRl_nXmpfNyaj9yMM4G46CT7n29jktARWb1GmVIHWeSLyMi1cMFwd9cvHBfba85dYnCprH9iyOy2ZLOemGx2fOw3ixRUU0GPiQmb4cZyw0K4tWcFqa-xy',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA5uuwct9DRGsuTvQOElQTQs0CtR9j1TiQYYQj-0iEFOJKQU_KBFsEEgZPJHjT9apf99AqR0u-88CZnSRzfa0GoGN9tElxdDUWlnq2yt9vOu-nNYxI6joyVMXVBYSykMTIKI7SiOp7ZDtVBNU0WrWTJ1YCaEtur_UOE8CVxLY4dR7vK3ixaIRhWHiqxzMjkU4OpfBobQALi3mXT2hUMm98dq_VA69LvFo0ciNWha_WH0C1Z0SaZhj4P',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBnxoqluK4achK5yUtDJ4rU0qfNUAwuMD18yfsFNwPLvoSB0qowJid8_hHA1DLbWZjHTfoGIJjfhqY9EF4Njkpeqm0TqwlV2RiCGHahg7QodD0AeMWS-xGca7442ln3h8GIme7W2qKtXYmh2r875BryB2XwcHD-vvo0bdEjIgkCDV-doQ4_UCu1OE0yHoWowukPxVa-Jdg6R37VRwFbILrVPbwOMc8R2y3s2ztJdUctS-gF3moVvnd_',
    ],
    description: 'Sculptural cowl-back evening gown hand-draped from heavy 22-momme Rajshahi mulberry silk. Designed with an invisible corset framework and cascading silk train.',
    composition: '100% Pure Mulberry Silk (22-Momme heavy weight weave), Italian cupro lining',
    provenance: 'Woven on historic Rajshahi handlooms; tailored in Maison Chattogram GEC Atelier.',
    care: 'Specialist organic dry clean only. Store in complimentary archival cotton garment bag.',
    tailoringNotes: 'Includes complimentary 28-point bespoke alteration at our Chattogram Salon or Dhaka Suite.',
    sizes: ['38 / XS', '40 / S', '42 / M', '44 / L', 'Bespoke M2M'],
    fits: ['Fluid Draped', 'Architectural Slim'],
    colors: [
      { name: 'Obsidian Noir', hex: '#121212', preview: '#121212' },
      { name: 'Royal Cobalt', hex: '#103FEF', preview: '#103FEF' },
      { name: 'Alabaster Ivory', hex: '#FBF9F8', preview: '#F5F2EE' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 25,
  },
  {
    id: 'handwoven-jamdani-cape',
    title: 'Hand-woven Jamdani Cape',
    edition: 'Edition 02 • Heritage Masterpiece',
    category: 'Women',
    subcategory: 'Capes & Outerwear',
    silhouette: 'Fluid Draped',
    fabric: 'Heritage 200-Count Jamdani Muslin',
    priceBDT: 29500,
    priceUSD: 250,
    vipPriceBDT: 25075,
    vipPriceUSD: 212,
    badge: 'Artisan Heritage',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBnxoqluK4achK5yUtDJ4rU0qfNUAwuMD18yfsFNwPLvoSB0qowJid8_hHA1DLbWZjHTfoGIJjfhqY9EF4Njkpeqm0TqwlV2RiCGHahg7QodD0AeMWS-xGca7442ln3h8GIme7W2qKtXYmh2r875BryB2XwcHD-vvo0bdEjIgkCDV-doQ4_UCu1OE0yHoWowukPxVa-Jdg6R37VRwFbILrVPbwOMc8R2y3s2ztJdUctS-gF3moVvnd_',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA5uuwct9DRGsuTvQOElQTQs0CtR9j1TiQYYQj-0iEFOJKQU_KBFsEEgZPJHjT9apf99AqR0u-88CZnSRzfa0GoGN9tElxdDUWlnq2yt9vOu-nNYxI6joyVMXVBYSykMTIKI7SiOp7ZDtVBNU0WrWTJ1YCaEtur_UOE8CVxLY4dR7vK3ixaIRhWHiqxzMjkU4OpfBobQALi3mXT2hUMm98dq_VA69LvFo0ciNWha_WH0C1Z0SaZhj4P',
    ],
    description: 'An architectural evening cape celebrating UNESCO-recognized Jamdani weaving. Features 200-count geometric floral motifs hand-interwoven with fine metallic gold threads.',
    composition: '100% Hand-spun Bengal Cotton Muslin & Zari Metallic Threads',
    provenance: 'Woven over 180 hours on Shitalakshya riverbanks; finished at Maison Chattogram.',
    care: 'Museum-grade preservation dry clean only.',
    tailoringNotes: 'Dramatic high Mandarin collar with gold hook closure and weighted hem for ethereal sway.',
    sizes: ['40 / S', '42 / M', 'Bespoke M2M'],
    fits: ['Fluid Draped'],
    colors: [
      { name: 'Midnight Charcoal & Gold', hex: '#1C1B1B', preview: '#1C1B1B' },
      { name: 'Champagne Muslin', hex: '#FDDDB9', preview: '#E8D5C4' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 12,
  },
  {
    id: 'double-breasted-linen-blazer',
    title: 'Tailored Double-Breasted Linen Blazer',
    edition: 'Edition 03 • Maritime Sartorial',
    category: 'Women',
    subcategory: 'Tailoring & Blazers',
    silhouette: 'Structured Tailoring',
    fabric: 'Irish Riviera Linen & Silk',
    priceBDT: 16800,
    priceUSD: 140,
    vipPriceBDT: 14280,
    vipPriceUSD: 119,
    badge: 'Chattogram Port Riviera',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJUWQ_9FRY5jsSEkQYH0mpdQQvtHLSV584mR1K2gmj3qeRSqio-z41KTt1wnWYhvF3-dIrCZILEdQK6h7DBZjOtb7LgUogYz--2fviI7Dm1YtVy7Onn-l1K1FI0FIs1GqWolhPBJ2T_80H40wp60MvTFfp-Qoq9Zu24lk3JZz_28OcXrYiQrE1VKLRSwkG-XSo_dsccAk3itNvuSYNFy6D1tz0-8QugoIqNd7IGrdXqS_eOu2QEZO',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAtQRYe3HSpSkH6fBVb64n_uDA0AjbPTKuRCWAVzGZhjh6ST7Htod1UPInaOoDrHnng6ZToV0pDMnxa_33sSqsU3Uh8TilUr-rwcyd2rtTdSDn6LqcSXPNWSpQP1HiylMohRl_nXmpfNyaj9yMM4G46CT7n29jktARWb1GmVIHWeSLyMi1cMFwd9cvHBfba85dYnCprH9iyOy2ZLOemGx2fOw3ixRUU0GPiQmb4cZyw0K4tWcFqa-xy',
    ],
    description: 'Sharp maritime double-breasted silhouette tailored from high-density Irish Riviera linen and raw silk. Finished with nautical brushed horn buttons and peak lapels.',
    composition: '75% Irish Linen, 25% Raw Mulberry Silk (310gsm)',
    provenance: 'Woven in Belfast; structured tailoring completed at Blu Eyes Atelier Chattogram.',
    care: 'Dry clean only. Press with medium steam.',
    tailoringNotes: 'Sculpted waistline with functional surgeon cuffs and dual rear vents.',
    sizes: ['38 / XS', '40 / S', '42 / M', '44 / L'],
    fits: ['Structured Tailoring', 'Architectural Slim'],
    colors: [
      { name: 'Nautical Navy', hex: '#002BBB', preview: '#002BBB' },
      { name: 'Alabaster Chalk', hex: '#FCF9F8', preview: '#F0EDEC' },
      { name: 'Bronze Sand', hex: '#715A3E', preview: '#715A3E' },
    ],
    inStock: true,
    isLimited: false,
  },

  // ==========================================
  // MEN (3+ distinct luxury garments)
  // ==========================================
  {
    id: 'imperial-raw-silk-panjabi',
    title: 'Imperial Rajshahi Raw Silk Panjabi',
    edition: 'Edition 04 • Heritage Ceremonial',
    category: 'Men',
    subcategory: 'Panjabi & Kurta',
    silhouette: 'Relaxed Atelier',
    fabric: 'Handspun Tussar Raw Silk',
    priceBDT: 14200,
    priceUSD: 120,
    vipPriceBDT: 12070,
    vipPriceUSD: 102,
    badge: 'Artisan Heritage',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA3SBb2VGDIlSdc4du1lpqnligPhARREv_bEv703ibLNpinfPGkYu3SpJNTRlAqm-PUQCVIoaKZwipqEOlD3mx6pVO5pf2ApY8Ga1lz2OxE9bcyHXNG8gmcr6bCypd6C9S1-v5eec5xG_odmPVtPEEmWzKxJtOozbBB7MhfrUj9p1u6rp_YdKFxUoLx8C9Wcm_J-EnGpDffOlesMA8-OacujRZoAlcVJg4m2dj24fqerQxVedknTqdu',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJUWQ_9FRY5jsSEkQYH0mpdQQvtHLSV584mR1K2gmj3qeRSqio-z41KTt1wnWYhvF3-dIrCZILEdQK6h7DBZjOtb7LgUogYz--2fviI7Dm1YtVy7Onn-l1K1FI0FIs1GqWolhPBJ2T_80H40wp60MvTFfp-Qoq9Zu24lk3JZz_28OcXrYiQrE1VKLRSwkG-XSo_dsccAk3itNvuSYNFy6D1tz0-8QugoIqNd7IGrdXqS_eOu2QEZO',
    ],
    description: 'Heritage handspun Tussar raw silk Panjabi with discreet bronze micro-stitch details along the structured band collar and concealed hand-carved mother-of-pearl placket.',
    composition: '100% Hand-spun Rajshahi Raw Tussar Silk, Mother-of-Pearl buttons',
    provenance: 'Rajshahi silk looms; crafted by legacy master tailors at Maison Chattogram.',
    care: 'Dry clean only. Press with medium iron over pressing cloth.',
    tailoringNotes: 'Engineered ergonomic armhole depth for regal poise and comfort during coastal galas.',
    sizes: ['38 / XS', '40 / S', '42 / M', '44 / L', '46 / XL', 'Bespoke M2M'],
    fits: ['Relaxed Atelier', 'Architectural Slim'],
    colors: [
      { name: 'Raw Champagne', hex: '#E0C29F', preview: '#E0C29F' },
      { name: 'Midnight Obsidian', hex: '#1C1B1B', preview: '#1C1B1B' },
      { name: 'Royal Indigo', hex: '#103FEF', preview: '#103FEF' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 30,
  },
  {
    id: 'super-160s-wool-tuxedo',
    title: 'Super 160s Wool Evening Tuxedo',
    edition: 'Edition 05 • Bespoke Black Tie',
    category: 'Men',
    subcategory: 'Suits & Tuxedos',
    silhouette: 'Structured Tailoring',
    fabric: 'Biella Super 160s Merino Wool',
    priceBDT: 34000,
    priceUSD: 285,
    vipPriceBDT: 28900,
    vipPriceUSD: 242,
    badge: 'Black Tie Gala',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAajgUsyVm0BDFqXbmsfTNwOIOHX_-XU_cVNbfml_P2xzL1wkJVh5VoOilmngj4kBGGJX6hzUSfBoNb3_bdSBsysR2c1ofleC9VwLz6W4-XpjGq3aY4-K549dKtwRh6evxXJCvcsQeOxWXtyfV4zPEz-JLH5hCpLiF3HLU0Vgg6gMjPZH0AsvaRYJ5CJIqkUKCF1VaWnnEBnzGTytw5oVmisBdXFBWPnU0wokCumKYCpJBNL0VqRqg4',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJUWQ_9FRY5jsSEkQYH0mpdQQvtHLSV584mR1K2gmj3qeRSqio-z41KTt1wnWYhvF3-dIrCZILEdQK6h7DBZjOtb7LgUogYz--2fviI7Dm1YtVy7Onn-l1K1FI0FIs1GqWolhPBJ2T_80H40wp60MvTFfp-Qoq9Zu24lk3JZz_28OcXrYiQrE1VKLRSwkG-XSo_dsccAk3itNvuSYNFy6D1tz0-8QugoIqNd7IGrdXqS_eOu2QEZO',
    ],
    description: 'Masterfully sculpted evening tuxedo featuring midnight silk grosgrain shawl lapel, hand-stitched barchetta breast pocket, and unlined high-twist trousers with silk side braid.',
    composition: 'Super 160s Australian Merino Wool woven in Biella, Italy; Silk grosgrain trim',
    provenance: 'Full floating canvas architecture crafted by Master Cutters at Maison Chattogram.',
    care: 'Professional bespoke valet press and dry clean.',
    tailoringNotes: 'Roped sleevehead architecture with horn buttons and hand-worked boutonnière.',
    sizes: ['38 / XS', '40 / S', '42 / M', '44 / L', '46 / XL', 'Bespoke M2M'],
    fits: ['Structured Tailoring', 'Architectural Slim'],
    colors: [
      { name: 'Cobalt Midnight', hex: '#0A257A', preview: '#0A257A' },
      { name: 'Obsidian Noir', hex: '#121212', preview: '#121212' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 20,
  },
  {
    id: 'egyptian-giza-cotton-shirt',
    title: 'Egyptian Giza Cotton Monogram Shirt',
    edition: 'Edition 06 • Sartorial Daily',
    category: 'Men',
    subcategory: 'Formal Shirts',
    silhouette: 'Architectural Slim',
    fabric: 'Giza 87 Double-Twisted Cotton',
    priceBDT: 8500,
    priceUSD: 72,
    vipPriceBDT: 7225,
    vipPriceUSD: 61,
    badge: 'Giza 87 Cotton',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJUWQ_9FRY5jsSEkQYH0mpdQQvtHLSV584mR1K2gmj3qeRSqio-z41KTt1wnWYhvF3-dIrCZILEdQK6h7DBZjOtb7LgUogYz--2fviI7Dm1YtVy7Onn-l1K1FI0FIs1GqWolhPBJ2T_80H40wp60MvTFfp-Qoq9Zu24lk3JZz_28OcXrYiQrE1VKLRSwkG-XSo_dsccAk3itNvuSYNFy6D1tz0-8QugoIqNd7IGrdXqS_eOu2QEZO',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA3SBb2VGDIlSdc4du1lpqnligPhARREv_bEv703ibLNpinfPGkYu3SpJNTRlAqm-PUQCVIoaKZwipqEOlD3mx6pVO5pf2ApY8Ga1lz2OxE9bcyHXNG8gmcr6bCypd6C9S1-v5eec5xG_odmPVtPEEmWzKxJtOozbBB7MhfrUj9p1u6rp_YdKFxUoLx8C9Wcm_J-EnGpDffOlesMA8-OacujRZoAlcVJg4m2dj24fqerQxVedknTqdu',
    ],
    description: 'Crisp ceremonial dress shirt crafted from long-staple Egyptian Giza 87 cotton with French double cuffs, removable collar stays, and bespoke hand-embroidered patron monogram.',
    composition: '100% Egyptian Giza 87 Extra-Long Staple Cotton (140/2 ply)',
    provenance: 'Spun in Alexandria; custom monogramming completed at Chattogram GEC Atelier.',
    care: 'Warm machine wash, line dry, hot steam iron.',
    tailoringNotes: 'Semi-spread British spread collar optimized for four-in-hand and bow ties.',
    sizes: ['38 / XS', '40 / S', '42 / M', '44 / L', '46 / XL'],
    fits: ['Architectural Slim', 'Classic Tailored'],
    colors: [
      { name: 'Optical White', hex: '#FFFFFF', preview: '#FFFFFF' },
      { name: 'Port Sky Blue', hex: '#C6CDFF', preview: '#C6CDFF' },
    ],
    inStock: true,
    isLimited: false,
  },

  // ==========================================
  // KIDS (2–15Y) (3+ distinct luxury garments)
  // ==========================================
  {
    id: 'royal-velvet-kids-sherwani',
    title: 'Royal Velvet Festive Sherwani & Waistcoat Set',
    edition: 'Edition 07 • Kids Festive Gala',
    category: 'Kids',
    subcategory: 'Ceremonial & Sherwanis',
    silhouette: 'Traditional Royal',
    fabric: 'Micro-Silk Velvet & Tussar Silk',
    priceBDT: 11800,
    priceUSD: 98,
    vipPriceBDT: 10030,
    vipPriceUSD: 83,
    badge: 'Festive Ceremonial',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
    ],
    description: 'Festive 3-piece set comprising an architectural micro-velvet waistcoat with gold zari piping, ivory raw silk kurta, and tailored churidar trousers designed for weddings and festivities.',
    composition: 'Silk-blend micro velvet waistcoat, 100% breathable organic cotton lining',
    provenance: 'Handcrafted in Chattogram Atelier with non-scratch hidden seams.',
    care: 'Dry clean only.',
    tailoringNotes: 'Includes expandable interior side-seams allowing 1.5 inches of natural growth.',
    sizes: ['2-4Y', '5-7Y', '8-11Y', '12-15Y'],
    fits: ['Traditional Royal'],
    colors: [
      { name: 'Royal Sapphire', hex: '#103FEF', preview: '#103FEF' },
      { name: 'Imperial Emerald', hex: '#1A4D2E', preview: '#1A4D2E' },
      { name: 'Champagne Gold', hex: '#8C7355', preview: '#8C7355' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 20,
  },
  {
    id: 'silk-pleated-party-frock',
    title: 'Silk Pleated Formal Party Frock',
    edition: 'Edition 08 • Young Mademoiselle',
    category: 'Kids',
    subcategory: 'Dresses & Frocks',
    silhouette: 'Fluid Draped',
    fabric: 'Mulberry Silk Organza & Satin',
    priceBDT: 9800,
    priceUSD: 82,
    vipPriceBDT: 8330,
    vipPriceUSD: 70,
    badge: 'Hand-Pleated',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
    ],
    description: 'Ethereal hand-pleated silk organza party dress with delicate pearl button detailing, oversized satin sash bow at back, and soft multi-tier cotton tulle underskirt.',
    composition: '100% Silk Organza shell, 100% OEKO-TEX certified soft cotton voile lining',
    provenance: 'Pattern-cut and hand-finished at Blu Eyes Atelier Nasirabad salon.',
    care: 'Dry clean or gentle hand wash cold with silk detergent.',
    tailoringNotes: 'Concealed zipper with interior velvet protective flap.',
    sizes: ['2-4Y', '5-7Y', '8-11Y', '12-15Y'],
    fits: ['Fluid Draped'],
    colors: [
      { name: 'Dusty Rose Quartz', hex: '#E8B4B8', preview: '#E8B4B8' },
      { name: 'Ivory Pearl', hex: '#FCF9F8', preview: '#F7F5F0' },
    ],
    inStock: true,
    isLimited: false,
  },
  {
    id: 'tailored-linen-trousers-kids',
    title: 'Tailored Linen Riviera Trousers',
    edition: 'Edition 09 • Young Gentleman',
    category: 'Kids',
    subcategory: 'Trousers & Shorts',
    silhouette: 'Classic Tailored',
    fabric: 'Pure French Coastal Linen',
    priceBDT: 6200,
    priceUSD: 52,
    vipPriceBDT: 5270,
    vipPriceUSD: 44,
    badge: 'Coastal Riviera',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJUWQ_9FRY5jsSEkQYH0mpdQQvtHLSV584mR1K2gmj3qeRSqio-z41KTt1wnWYhvF3-dIrCZILEdQK6h7DBZjOtb7LgUogYz--2fviI7Dm1YtVy7Onn-l1K1FI0FIs1GqWolhPBJ2T_80H40wp60MvTFfp-Qoq9Zu24lk3JZz_28OcXrYiQrE1VKLRSwkG-XSo_dsccAk3itNvuSYNFy6D1tz0-8QugoIqNd7IGrdXqS_eOu2QEZO',
    ],
    description: 'Relaxed tailored flat-front trousers with adjustable elastic interior waistband, slash pockets, and turn-up hems tailored from washed French linen.',
    composition: '100% Pure Normandy Linen (pre-washed for cloud softness)',
    provenance: 'Tailored in Maison Chattogram workshop.',
    care: 'Machine wash delicate cold. Tumble dry low or air dry.',
    tailoringNotes: 'Generous turn-up cuff can be let down as child grows.',
    sizes: ['2-4Y', '5-7Y', '8-11Y', '12-15Y'],
    fits: ['Classic Tailored'],
    colors: [
      { name: 'Karnaphuli Sand', hex: '#E0C29F', preview: '#E0C29F' },
      { name: 'Port Indigo Navy', hex: '#002BBB', preview: '#002BBB' },
    ],
    inStock: true,
    isLimited: false,
  },

  // ==========================================
  // BABY (0–2Y) (3+ distinct luxury items)
  // ==========================================
  {
    id: 'organic-silk-cotton-layette-box',
    title: '8-Piece Organic Silk-Cotton Layette Box',
    edition: 'Edition 10 • Heirloom Welcome Set',
    category: 'Baby',
    subcategory: 'Layette & Gift Sets',
    silhouette: 'Relaxed Atelier',
    fabric: 'Organic Silk & GOTS Egyptian Cotton',
    priceBDT: 12500,
    priceUSD: 105,
    vipPriceBDT: 10625,
    vipPriceUSD: 89,
    badge: 'Luxury Newborn Gift',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
    ],
    description: 'Sumptuous 8-piece newborn gift suite presented in our signature embossed wooden keepsake box. Includes kimono top, footed pant, receiving wrap, bonnet, mittens, booties, and silk bib.',
    composition: '50% Mulberry Silk, 50% GOTS-Certified Organic Egyptian Cotton',
    provenance: 'Hypoallergenic botanical dying; packaged by hand in Maison Chattogram.',
    care: 'Gentle machine wash cold with organic baby detergent.',
    tailoringNotes: 'Zero interior tags and reverse flat-lock seams to protect sensitive newborn skin.',
    sizes: ['0-6M', '6-12M'],
    fits: ['Relaxed Atelier'],
    colors: [
      { name: 'Heirloom Milk & Gold', hex: '#FCF9F8', preview: '#FFFDF9' },
      { name: 'Chittagong Dawn Blue', hex: '#C6CDFF', preview: '#C6CDFF' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 40,
  },
  {
    id: 'hand-embroidered-muslin-romper',
    title: 'Hand-embroidered Muslin Romper',
    edition: 'Edition 11 • Artisanal Baby',
    category: 'Baby',
    subcategory: 'Rompers & Onesies',
    silhouette: 'Relaxed Atelier',
    fabric: 'Ultra-Fine Bengal Khadi Muslin',
    priceBDT: 5400,
    priceUSD: 45,
    vipPriceBDT: 4590,
    vipPriceUSD: 38,
    badge: 'Artisan Needlework',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
    ],
    description: 'Featherweight breathable pure muslin romper adorned with delicate hand-embroidered floral vines on the smocked chest and genuine mother-of-pearl snap closures.',
    composition: '100% Handloomed Bengal Khadi Muslin Cotton',
    provenance: 'Embroidery stitched by traditional women artisans in rural Chattogram communities.',
    care: 'Hand wash cold or delicate cycle.',
    tailoringNotes: 'Generous diaper room with nickel-free snaps for effortless changing.',
    sizes: ['0-6M', '6-12M', '12-24M'],
    fits: ['Relaxed Atelier'],
    colors: [
      { name: 'Pure Chalk Muslin', hex: '#F6F3F2', preview: '#FFFFFF' },
      { name: 'Sage Leaf', hex: '#A3B899', preview: '#A3B899' },
    ],
    inStock: true,
    isLimited: false,
  },
  {
    id: 'heirloom-cashmere-receiving-blanket',
    title: 'Heirloom Cashmere Receiving Blanket',
    edition: 'Edition 12 • Baby Couture',
    category: 'Baby',
    subcategory: 'Blankets & Swaddles',
    silhouette: 'Relaxed Atelier',
    fabric: 'Pure Grade-A Mongolian Cashmere',
    priceBDT: 8900,
    priceUSD: 75,
    vipPriceBDT: 7565,
    vipPriceUSD: 64,
    badge: '100% Cashmere',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
    ],
    description: 'Cloud-spun pure baby cashmere swaddling blanket featuring a cable-knit border and personalized hand-embroidered patron monogram emblem.',
    composition: '100% Grade-A Mongolian Organic Baby Cashmere',
    provenance: 'Carded in Mongolia; tailored and monogrammed in Maison Chattogram.',
    care: 'Hand wash cold with cashmere shampoo, lay flat on towel to dry.',
    tailoringNotes: 'Generous 100cm x 100cm size designed to transition from crib swaddle to heirloom nursery keepsake.',
    sizes: ['One Size'],
    fits: ['Relaxed Atelier'],
    colors: [
      { name: 'Oatmeal Heather', hex: '#E0C29F', preview: '#E8D5C4' },
      { name: 'Soft Powder Sky', hex: '#BAC3FF', preview: '#BAC3FF' },
      { name: 'Cloud White', hex: '#FFFFFF', preview: '#FFFFFF' },
    ],
    inStock: true,
    isLimited: false,
  },

  // ==========================================
  // ACCESSORIES (3+ distinct luxury items)
  // ==========================================
  {
    id: 'hammered-gold-cufflinks',
    title: 'Hand-hammered 24K Gold-Plated Cufflinks',
    edition: 'Edition 13 • Atelier Joaillerie',
    category: 'Accessories',
    subcategory: 'Fine Jewelry',
    silhouette: 'Structured Tailoring',
    fabric: '24K Gold Plated Solid Brass',
    priceBDT: 8500,
    priceUSD: 72,
    vipPriceBDT: 7225,
    vipPriceUSD: 61,
    badge: '24K Gold Plated',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBq0v8IK0PvEq7OsWWP7K7eeyXNROby2pFC6_yPSHXT5BByHKs6o-LRjB0NVX1c0nbURnbNBjmrxYJNrBT8UBSivYh3Wv_IJMVEffHzZWhdf2_wSbQCau3PbNw6L8Uqcpg3brsfSopoU-1ZwySE2X41O-23Q6OW7FjtQQ95o6wfvEwwHKLOBB-2VDfyGfOIuSudZA85dBJxm2_BKPwTZhR1LioY3Z7w0EmcbKLmSATUKPtzcogVWMep',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCNbdQxOLMk13Q112osmHRF7lu18hw17GiMjgqIVV5w7RUNUXL-8gcarkUNamazbuo_s6wuoFjJyxQBGG8mn3H8JYDgy0pmy5OMsorSpefnTW-1bW5EordHubE5_N8n9pGCv6UnWYQ3mpR0Rmmb-j5iLbTmD_ZwizFhYz-2124InXEZOuSdpNJN5PwJYcsuJKI6VWH10LPKG6dUfBOkHu-pXLNk0OU3A7wsEMW7ZFe-oocPza7Cu-0O',
    ],
    description: 'Sculptural square cufflinks hand-forged from jeweler-grade brass, heavy 24K yellow gold electroplating, and centered with an untreated sapphire accent stone.',
    composition: '24K Yellow Gold heavy electroplate, Jeweler brass, Untreated sapphire',
    provenance: 'Forged by generational goldsmiths in the historic Terribazar quarter of Chattogram.',
    care: 'Store in anti-tarnish velvet pouch provided. Buff with jewelry cloth.',
    tailoringNotes: 'Swivel whaleback toggle mechanism engineered for French cuffs.',
    sizes: ['One Size'],
    fits: ['Structured Tailoring'],
    colors: [
      { name: '24K Yellow Gold', hex: '#8C7355', preview: '#D4AF37' },
      { name: 'Obsidian Rhodium', hex: '#1C1B1B', preview: '#2B2B2B' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 50,
  },
  {
    id: 'italian-leather-weekender-bag',
    title: 'Full-Grain Italian Leather Weekender Bag',
    edition: 'Edition 14 • Maroquinerie',
    category: 'Accessories',
    subcategory: 'Leather Goods & Travel',
    silhouette: 'Classic Tailored',
    fabric: 'Vegetable-Tanned Tuscan Calfskin',
    priceBDT: 38500,
    priceUSD: 325,
    vipPriceBDT: 32725,
    vipPriceUSD: 276,
    badge: 'Tuscan Leather',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBq0v8IK0PvEq7OsWWP7K7eeyXNROby2pFC6_yPSHXT5BByHKs6o-LRjB0NVX1c0nbURnbNBjmrxYJNrBT8UBSivYh3Wv_IJMVEffHzZWhdf2_wSbQCau3PbNw6L8Uqcpg3brsfSopoU-1ZwySE2X41O-23Q6OW7FjtQQ95o6wfvEwwHKLOBB-2VDfyGfOIuSudZA85dBJxm2_BKPwTZhR1LioY3Z7w0EmcbKLmSATUKPtzcogVWMep',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAajgUsyVm0BDFqXbmsfTNwOIOHX_-XU_cVNbfml_P2xzL1wkJVh5VoOilmngj4kBGGJX6hzUSfBoNb3_bdSBsysR2c1ofleC9VwLz6W4-XpjGq3aY4-K549dKtwRh6evxXJCvcsQeOxWXtyfV4zPEz-JLH5hCpLiF3HLU0Vgg6gMjPZH0AsvaRYJ5CJIqkUKCF1VaWnnEBnzGTytw5oVmisBdXFBWPnU0wokCumKYCpJBNL0VqRqg4',
    ],
    description: 'Heirloom travel duffel bag hand-stitched from full-grain vegetable-tanned Tuscan calfskin. Features solid brushed brass hardware, dual rolled leather handles, and a detachable padded shoulder strap.',
    composition: '100% Full-Grain Tuscan Vegetable-Tanned Leather, Waterproof British canvas lining',
    provenance: 'Tanned in Santa Croce, Italy; assembled by artisan leather crafters in Maison Chattogram.',
    care: 'Treat biannually with natural beeswax leather balsam.',
    tailoringNotes: 'Reinforced leather base with 5 protective solid brass feet. Meets international airline cabin specs.',
    sizes: ['One Size'],
    fits: ['Classic Tailored'],
    colors: [
      { name: 'Cognac Saddle', hex: '#715A3E', preview: '#8C5835' },
      { name: 'Midnight Obsidian', hex: '#1C1B1B', preview: '#1C1B1B' },
    ],
    inStock: true,
    isLimited: true,
    limitedCount: 18,
  },
  {
    id: 'hand-spun-pashmina-shawl',
    title: 'Hand-spun Royal Pashmina Shawl',
    edition: 'Edition 15 • Cashmere Heritage',
    category: 'Accessories',
    subcategory: 'Scarves & Wraps',
    silhouette: 'Fluid Draped',
    fabric: 'Pure Himalayan Changthangi Pashmina',
    priceBDT: 19500,
    priceUSD: 165,
    vipPriceBDT: 16575,
    vipPriceUSD: 140,
    badge: 'Grade-A Pashmina',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCNbdQxOLMk13Q112osmHRF7lu18hw17GiMjgqIVV5w7RUNUXL-8gcarkUNamazbuo_s6wuoFjJyxQBGG8mn3H8JYDgy0pmy5OMsorSpefnTW-1bW5EordHubE5_N8n9pGCv6UnWYQ3mpR0Rmmb-j5iLbTmD_ZwizFhYz-2124InXEZOuSdpNJN5PwJYcsuJKI6VWH10LPKG6dUfBOkHu-pXLNk0OU3A7wsEMW7ZFe-oocPza7Cu-0O',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
    ],
    description: 'Pure 100% Changthangi goat pashmina hand-spun on traditional wooden charkhas. Lightweight warmth passing effortlessly through a bespoke ring, with fine hand-twisted fringe.',
    composition: '100% Authentic Grade-A Himalayan Pashmina (12-14 microns)',
    provenance: 'Spun in Ladakh; hand-dyed with natural botanical indigo in Maison Chattogram.',
    care: 'Dry clean or hand wash cold with wool wash. Dry flat.',
    tailoringNotes: 'Generous 210cm x 100cm wrap proportions for evening galas.',
    sizes: ['One Size'],
    fits: ['Fluid Draped'],
    colors: [
      { name: 'Royal Indigo', hex: '#103FEF', preview: '#103FEF' },
      { name: 'Champagne Bronze', hex: '#8C7355', preview: '#8C7355' },
      { name: 'Smoky Charcoal', hex: '#313030', preview: '#313030' },
    ],
    inStock: true,
    isLimited: false,
  },
]

export const DEMOGRAPHIC_PILLS: { id: Demographic; label: string; sub: string; image: string }[] = [
  {
    id: 'Women',
    label: 'WOMEN',
    sub: 'Haute Couture',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnxoqluK4achK5yUtDJ4rU0qfNUAwuMD18yfsFNwPLvoSB0qowJid8_hHA1DLbWZjHTfoGIJjfhqY9EF4Njkpeqm0TqwlV2RiCGHahg7QodD0AeMWS-xGca7442ln3h8GIme7W2qKtXYmh2r875BryB2XwcHD-vvo0bdEjIgkCDV-doQ4_UCu1OE0yHoWowukPxVa-Jdg6R37VRwFbILrVPbwOMc8R2y3s2ztJdUctS-gF3moVvnd_',
  },
  {
    id: 'Men',
    label: 'MEN',
    sub: 'Bespoke Tailoring',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3SBb2VGDIlSdc4du1lpqnligPhARREv_bEv703ibLNpinfPGkYu3SpJNTRlAqm-PUQCVIoaKZwipqEOlD3mx6pVO5pf2ApY8Ga1lz2OxE9bcyHXNG8gmcr6bCypd6C9S1-v5eec5xG_odmPVtPEEmWzKxJtOozbBB7MhfrUj9p1u6rp_YdKFxUoLx8C9Wcm_J-EnGpDffOlesMA8-OacujRZoAlcVJg4m2dj24fqerQxVedknTqdu',
  },
  {
    id: 'Kids',
    label: 'KIDS',
    sub: '2–15Y Festive',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCN1PgQxGKVWDIVugVMxaWp1diY25WGFTUazbOKQvVUYdcC4XNFHntH-zbvAsVY04oVUbARtMfVh5d73O66yZAvu5PPxIwPf7QyvHxUuhFnooezDRwHadCSkbpq3c9y1Y6XBh_oBRneHjD7y9zwJO3rkYs26JSFkNIqkpuM0R0Sh3iE8BajbP6hTrknvRYAch2ybfws4jJ_dPoO12OJZDlPpkYwr5hoEYZNW_e_CceHiOax84-e3RQM',
  },
  {
    id: 'Baby',
    label: 'BABY',
    sub: '0–2Y Heirloom',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBG6CHJA23sNP6ryl09Bw8CgJeX7AXNn4DqKcnvLkxRiP5wkQllwfk_me08S5UJU5kBJ1mu33ETdnuO1VvjlpdYR8iev8xcYaSEZaxKzH8a7J71GWG6K-192GGKydxGvRa_BwaulOnM8WYR3SucnCQbTd-fDKg2cT8dj1hWg0hZw0oOCm4LsFwoui4dS-7t7nu_O1d0OOaoq88b_CMqRytQ5Kx9CTLgGfEYMngLvfkS2XP4UvVq3JBW',
  },
  {
    id: 'Accessories',
    label: 'ACCESSORIES',
    sub: '24K Gold & Leather',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBq0v8IK0PvEq7OsWWP7K7eeyXNROby2pFC6_yPSHXT5BByHKs6o-LRjB0NVX1c0nbURnbNBjmrxYJNrBT8UBSivYh3Wv_IJMVEffHzZWhdf2_wSbQCau3PbNw6L8Uqcpg3brsfSopoU-1ZwySE2X41O-23Q6OW7FjtQQ95o6wfvEwwHKLOBB-2VDfyGfOIuSudZA85dBJxm2_BKPwTZhR1LioY3Z7w0EmcbKLmSATUKPtzcogVWMep',
  },
]

export const AUTOCOMPLETE_TAGS = [
  'Mulberry Silk Gown',
  'Jamdani Cape',
  'Linen Blazer',
  'Rajshahi Silk Panjabi',
  'Evening Tuxedo',
  'Giza Cotton Shirt',
  'Velvet Sherwani',
  'Silk Party Frock',
  'Organic Layette Box',
  'Muslin Romper',
  '24K Gold Cufflinks',
  'Leather Weekender',
  'Pashmina Shawl',
]
