import type { IndigoProduct } from './types'

export const INDIGO_PRODUCTS: IndigoProduct[] = [
  // --- WOMEN ---
  {
    id: 'ind-w-01',
    title: 'Hand-Woven Tangail Indigo Jamdani Saree',
    titleBn: 'হাতে বোনা টাঙ্গাইল নীল জামদানি শাড়ি',
    category: 'Women',
    craftTag: 'Tangail Master Loom',
    craftTagBn: 'টাঙ্গাইল মাস্টার লুম',
    artisanOrigin: 'Bajitpur Village, Tangail',
    artisanOriginBn: 'বাজিতপুর গ্রাম, টাঙ্গাইল',
    fabric: '100% Fine Mulberry Silk & Organic Cotton Zari',
    fabricBn: '১০০% খাঁটি রেশম সিল্ক এবং অর্গানিক কটন জরি',
    weaveTimeDays: 24,
    priceBDT: 16500,
    priceUSD: 140,
    isHero: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Woven by a 4th-generation master weaver on traditional wooden pit looms over 24 continuous days. Features authentic floral karigari motifs in unbleached gold zari over deep botanical indigo fermentation.',
    descriptionBn:
      'টানা ২৪ দিন ধরে প্রাচীন কাঠের গর্ত তাঁতে বোনা অনন্য জামদানি শাড়ি। গাঢ় প্রাকৃতিক নীলের জমিনে সোনালী জরির নিখুঁত ফুল ও লতাপাতার নকশা।',
    features: [
      'Authentic natural indigo leaf vat fermentation',
      'Hand-twisted 100-count combed warp and weft',
      'Includes unstitched pure silk blouse piece (80 cm)',
      'Dry clean only; store wrapped in unbleached muslin',
    ],
    featuresBn: [
      '১০০% খাঁটি ভেষজ নীল পাতার গাঁজনে রঙ করা',
      'হাতে পাকানো ১০০ কাউন্ট সুতার নিপুণ বুনন',
      'সাথে রয়েছে খাঁটি সিল্কের ব্লাউজ পিস (৮০ সেমি)',
      'শুধু ড্রাই ক্লিন প্রযোজ্য; মসলিন কাপড়ে সংরক্ষণ করুন',
    ],
    sizes: ['Free Size (5.5m + 0.8m)'],
    sizeMeasurements: [
      { size: 'Standard Saree', length: '5.5 Meters', waist: 'Adjustable', hips: 'Free' },
    ],
    colors: [
      { name: 'Deep Bengal Indigo', nameBn: 'গাঢ় বেঙ্গল ইন্ডিগো', hex: '#0A4269' },
      { name: 'Terracotta Zari Accent', nameBn: 'টেরাকোটা জরি', hex: '#B85324' },
    ],
    inStock: true,
  },
  {
    id: 'ind-w-02',
    title: 'Dual-Tone Raw Silk Festive Kurti Set',
    titleBn: 'ডুয়াল-টোন র সিল্ক ফেস্টিভ কুর্তি সেট',
    category: 'Women',
    craftTag: 'Rajshahi Silk',
    craftTagBn: 'রাজশাহী সিল্ক',
    artisanOrigin: 'Sopura Cluster, Rajshahi',
    artisanOriginBn: 'সোপুরা ক্লাস্টার, রাজশাহী',
    fabric: 'Pure Rajshahi Matka Silk & Handloom Cotton Trousers',
    fabricBn: 'খাঁটি রাজশাহী মটকা সিল্ক ও তাঁতের সুতি ট্রাউজার',
    weaveTimeDays: 9,
    priceBDT: 6200,
    priceUSD: 52,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'A structured A-line festival silhouette dyed with indigo and madder root. Embellished with subtle tonal Kantha stitch embroidery across the jewel neckline and sleeve hems.',
    descriptionBn:
      'ইন্ডিগো ও মঞ্জিষ্ঠার প্রাকৃতিক রঙে রঙিন এ-লাইন কাটের উৎসবমুখর কুর্তি। গলার অংশে ও হাতায় রয়েছে সুক্ষ্ম কাঁথা স্টিচের সুতার কাজ।',
    features: [
      'Hand-reeled raw silk with distinctive tactile slub texture',
      'Side concealed pockets and coconut shell button closure',
      'Comes with straight-cut ivory handloom cotton trousers',
    ],
    featuresBn: [
      'হাতে টানা র সিল্কের প্রাকৃতিক টেক্সচারযুক্ত ফেব্রিক',
      'লুকানো সাইড পকেট ও নারকেলের শেলের বোতাম',
      'সাথে রয়েছে আইভরি রঙের সুতি তাঁতের স্ট্রেইট ট্রাউজার',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    sizeMeasurements: [
      { size: 'S', chest: '36"', length: '44"', waist: '32"', hips: '38"' },
      { size: 'M', chest: '38"', length: '44"', waist: '34"', hips: '40"' },
      { size: 'L', chest: '40"', length: '45"', waist: '36"', hips: '42"' },
      { size: 'XL', chest: '42"', length: '45"', waist: '38"', hips: '44"' },
    ],
    colors: [
      { name: 'Indigo & Terracotta Dual', nameBn: 'নীল ও টেরাকোটা', hex: '#0A4269' },
      { name: 'Henna Oat', nameBn: 'মেহেদি ওট', hex: '#C28238' },
    ],
    inStock: true,
  },
  {
    id: 'ind-w-03',
    title: 'Handloom Khadi Embroidered Cape',
    titleBn: 'হাতে বোনা খাদি এমব্রয়ডার্ড কেপ',
    category: 'Women',
    craftTag: 'Cumilla Khadi',
    craftTagBn: 'কুমিল্লা খাদি',
    artisanOrigin: 'Mainamati Khadi Co-op, Cumilla',
    artisanOriginBn: 'ময়নামতি খাদি সমবায়, কুমিল্লা',
    fabric: 'Unbleached Hand-Spun Khadi Cotton',
    fabricBn: 'হাতে কাটা দেশি খাদি সুতা',
    weaveTimeDays: 7,
    priceBDT: 4800,
    priceUSD: 40,
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Flowing unstructured drape cape woven on traditional fly-shuttle handlooms in Cumilla. Embellished with artisanal river-wave running stitches that celebrate the Karnaphuli river.',
    descriptionBn:
      'কুমিল্লার ঐতিহ্যবাহী তাঁতে বোনা খোলামেলা কেপ। কর্ণফুলী নদীর ঢেউয়ের অনুপ্রেরণায় হাতে সুঁই-সুতার নিখুঁত নকশা করা।',
    features: [
      'Breathable all-season unbleached cotton khadi',
      'Open front styling with handcrafted brass hook tie-up',
      'Naturally soft with every gentle hand wash',
    ],
    featuresBn: [
      'সব ঋতুর উপযোগী আরামদায়ক দেশি খাদি সুতি',
      'সামনে হাতে গড়া পিতলের হুক ও টাই-আপ ডিটেইল',
      'প্রতিটি ধোয়ার সাথে আরও নরম ও আরামদায়ক হয়ে ওঠে',
    ],
    sizes: ['Free Size'],
    sizeMeasurements: [
      { size: 'Free Size', chest: 'Free', length: '38"', waist: 'Free' },
    ],
    colors: [
      { name: 'Raw Silk Ivory', nameBn: 'কাঁচা রেশম আইভরি', hex: '#F9F6F0' },
      { name: 'Indigo River Line', nameBn: 'নীল নদী রেখা', hex: '#0A4269' },
    ],
    inStock: true,
  },

  // --- MEN ---
  {
    id: 'ind-m-01',
    title: 'Imperial Indigo Raw Silk Panjabi',
    titleBn: 'ইম্পেরিয়াল ইন্ডিগো র সিল্ক পাঞ্জাবি',
    category: 'Men',
    craftTag: '100% Pure Silk',
    craftTagBn: '১০০% খাঁটি রেশম সিল্ক',
    artisanOrigin: 'Mirganj Silk Looms, Rajshahi',
    artisanOriginBn: 'মীরগঞ্জ সিল্ক লুম, রাজশাহী',
    fabric: 'Pure Rajshahi Mulberry Raw Silk with Cotton Lining',
    fabricBn: 'খাঁটি রাজশাহী তুত রেশম সিল্ক ও সুতি লাইনিং',
    weaveTimeDays: 14,
    priceBDT: 6800,
    priceUSD: 58,
    isHero: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Regal South Asian tailored panjabi rendered in deep botanical indigo. Features a slim structured mandarin collar with antique brass thread embroidery and mother-of-pearl buttons.',
    descriptionBn:
      'রাজকীয় ভাবগাম্ভীর্যপূর্ণ র সিল্ক পাঞ্জাবি। ম্যান্ডারিন কলারের উপর প্রাচীন ব্রাস সুতার সূক্ষ্ম কারুকাজ এবং আসল মাদার-অফ-পার্লের বোতাম।',
    features: [
      'Natural indigo dye formulated with zero synthetic chemicals',
      'Breathable voile cotton lining inside collar and yoke',
      'Two functional side pockets with bar-tack reinforcement',
    ],
    featuresBn: [
      'কোনোরকম রাসায়নিক ছাড়া শতভাগ প্রাকৃতিক নীল রঙ',
      'কলার ও ইয়োকে নরম সুতি কাপড়ের আরামদায়ক লাইনিং',
      'দুপাশে মজবুত স্টিচের প্রশস্ত পকেট',
    ],
    sizes: ['38', '40', '42', '44'],
    sizeMeasurements: [
      { size: '38 (S)', chest: '40"', length: '40"', waist: '38"' },
      { size: '40 (M)', chest: '42"', length: '42"', waist: '40"' },
      { size: '42 (L)', chest: '44"', length: '44"', waist: '42"' },
      { size: '44 (XL)', chest: '46"', length: '45"', waist: '44"' },
    ],
    colors: [
      { name: 'Imperial Bengal Indigo', nameBn: 'ইম্পেরিয়াল ইন্ডিগো', hex: '#0A4269' },
      { name: 'Antique Brass Sheen', nameBn: 'ব্রাস শিন', hex: '#B85324' },
    ],
    inStock: true,
  },
  {
    id: 'ind-m-02',
    title: 'Hand-Spun Khadi Casual Panjabi',
    titleBn: 'হাতে কাটা খাদি ক্যাজুয়াল পাঞ্জাবি',
    category: 'Men',
    craftTag: 'Handloom Khadi',
    craftTagBn: 'হাতে বোনা খাদি',
    artisanOrigin: 'Chandina Village, Cumilla',
    artisanOriginBn: 'চান্দিনা গ্রাম, কুমিল্লা',
    fabric: '100% Hand-Spun Natural Khadi Cotton',
    fabricBn: '১০০% হাতে কাটা প্রাকৃতিক সুতি খাদি',
    weaveTimeDays: 6,
    priceBDT: 3400,
    priceUSD: 29,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'An everyday relaxed silhouette spun from organic local cotton. Light, aerated weave structure offers effortless cooling under Bengal heat while celebrating indigenous craft.',
    descriptionBn:
      'দৈনন্দিন ব্যবহারের উপযোগী আরামদায়ক খাদি পাঞ্জাবি। হালকা ও বাতাস চলাচল উপযোগী বুনন যা গরমে অত্যন্ত আরামদায়ক।',
    features: [
      'Hand-spun thread on wooden Charkha spindles',
      'Band collar with natural wooden buttons',
      'Reinforced side slits for fluid movement',
    ],
    featuresBn: [
      'কাঠের চরকায় কাটা খাঁটি দেশি সুতা',
      'ব্যান্ড কলারের সাথে প্রাকৃতিক কাঠের বোতাম',
      'সহজে হাঁটাচলার জন্য মজবুত সাইড স্লিট',
    ],
    sizes: ['38', '40', '42', '44'],
    sizeMeasurements: [
      { size: '38 (S)', chest: '40"', length: '40"', waist: '38"' },
      { size: '40 (M)', chest: '42"', length: '42"', waist: '40"' },
      { size: '42 (L)', chest: '44"', length: '44"', waist: '42"' },
      { size: '44 (XL)', chest: '46"', length: '45"', waist: '44"' },
    ],
    colors: [
      { name: 'Raw Silk Ivory', nameBn: 'কাঁচা রেশম আইভরি', hex: '#F9F6F0' },
      { name: 'Faded River Indigo', nameBn: 'নদী নীল', hex: '#3882B5' },
    ],
    inStock: true,
  },
  {
    id: 'ind-m-03',
    title: 'Tailored Linen-Silk Waistcoat / Kabli Set',
    titleBn: 'টেইলর্ড লিনেন-সিল্ক কোটি ও কাবলি সেট',
    category: 'Men',
    craftTag: 'Festive Edit',
    craftTagBn: 'ফেস্টিভ কালেকশন',
    artisanOrigin: 'Maison Chattogram Atelier',
    artisanOriginBn: 'মেসন চট্টগ্রাম অ্যাটেলিয়ার',
    fabric: 'Belgian Linen-Silk Blend Waistcoat with Silk Kabli',
    fabricBn: 'লিনেন-সিল্ক ব্লেন্ডের কোটি এবং খাঁটি সিল্কের কাবলি',
    weaveTimeDays: 11,
    priceBDT: 5900,
    priceUSD: 50,
    images: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'A distinguished two-piece ensemble combining an indigo-dyed linen-silk tailored vest with a crisp unbleached raw silk kabli panjabi and pajama set.',
    descriptionBn:
      'অভিজাত দুই পিসের উৎসব পোশাক। ইন্ডিগো ডায়েড লিনেন-সিল্কের কটি এবং কাঁচা রেশম সিল্কের কাবলি সেট।',
    features: [
      'Sculpted welt pockets with silk pocket square included',
      'Burnished brass medallion buttons along front placket',
      'Full matching straight-leg drawstring pajama included',
    ],
    featuresBn: [
      'বুকের পকেটে সিল্কের পকেট স্কয়ার সংযুক্ত',
      'সামনে অ্যান্টিক ব্রাস মেডেলিয়ন বোতামের কাজ',
      'সাথে মানানসই সোজা কাটের আরামদায়ক পায়জামা',
    ],
    sizes: ['38', '40', '42', '44'],
    sizeMeasurements: [
      { size: '38 (S)', chest: '40"', length: '40"', waist: '38"' },
      { size: '40 (M)', chest: '42"', length: '42"', waist: '40"' },
      { size: '42 (L)', chest: '44"', length: '44"', waist: '42"' },
      { size: '44 (XL)', chest: '46"', length: '45"', waist: '44"' },
    ],
    colors: [
      { name: 'Terracotta & Indigo', nameBn: 'টেরাকোটা ও নীল', hex: '#B85324' },
      { name: 'Midnight Charcoal', nameBn: 'মিডনাইট চারকোল', hex: '#26201C' },
    ],
    inStock: true,
  },

  // --- KIDS (2-15Y) ---
  {
    id: 'ind-k-01',
    title: "Junior Boys' Handloom Panjabi Set",
    titleBn: 'জুনিয়র বয়েজ হ্যান্ডলুম পাঞ্জাবি সেট',
    category: 'Kids',
    craftTag: 'Natural Indigo Dye',
    craftTagBn: 'প্রাকৃতিক নীল ডাই',
    artisanOrigin: 'Tangail Youth Guild',
    artisanOriginBn: 'টাঙ্গাইল তাঁত সমবায়',
    fabric: '100% Breathable Combed Cotton Khadi',
    fabricBn: '১০০% আরামদায়ক কম্বড সুতি খাদি',
    weaveTimeDays: 4,
    priceBDT: 2900,
    priceUSD: 25,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1471286174890-9c112ffca564?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      "A festive 'Mini-Me' version of our classic men's panjabi, scaled with kid-friendly ergonomic collar heights and flexible elastic waist cotton pajama bottoms.",
    descriptionBn:
      'ছোটদের জন্য বিশেষভাবে তৈরি উৎসবের পাঞ্জাবি। নরম কলার এবং সহজে পরার উপযোগী ইলাস্টিকযুক্ত সুতি পায়জামা।',
    features: [
      'Chemical-free natural plant dyes safe for delicate young skin',
      'Flat-felled anti-chafing seams inside',
      'Includes matching elasticated white pajama',
    ],
    featuresBn: [
      'শিশুর সংবেদনশীল ত্বকের জন্য নিরাপদ প্রাকৃতিক উদ্ভিজ্জ রঙ',
      'ভিতরে কোনো খসখসে ভাব ছাড়া মসৃণ ফিনিশিং',
      'সাথে ইলাস্টিকযুক্ত আরামদায়ক সাদা পায়জামা',
    ],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-12Y', '13-15Y'],
    sizeMeasurements: [
      { size: '2-3Y', chest: '24"', length: '22"', waist: '20"' },
      { size: '4-5Y', chest: '26"', length: '25"', waist: '22"' },
      { size: '6-7Y', chest: '28"', length: '28"', waist: '24"' },
      { size: '8-9Y', chest: '30"', length: '31"', waist: '26"' },
      { size: '10-12Y', chest: '33"', length: '34"', waist: '28"' },
      { size: '13-15Y', chest: '36"', length: '37"', waist: '30"' },
    ],
    colors: [
      { name: 'Bengal Indigo', nameBn: 'বেঙ্গল ইন্ডিগো', hex: '#0A4269' },
      { name: 'Warm Terracotta', nameBn: 'উষ্ণ টেরাকোটা', hex: '#B85324' },
    ],
    inStock: true,
    ageBracket: ['2-7Y', '8-15Y'],
  },
  {
    id: 'ind-k-02',
    title: "Junior Girls' Festive Jamdani Frock",
    titleBn: 'জুনিয়র গার্লস ফেস্টিভ জামদানি ফ্রক',
    category: 'Kids',
    craftTag: 'Traditional Weave',
    craftTagBn: 'ঐতিহ্যবাহী বুনন',
    artisanOrigin: 'Rupganj Weavers Colony',
    artisanOriginBn: 'রূপগঞ্জ তাঁত পল্লী',
    fabric: 'Pure Jamdani Muslin Cotton with Cotton Lawn Slip',
    fabricBn: 'খাঁটি জামদানি মসলিন কটন ও নরম সুতি আস্তরণ',
    weaveTimeDays: 8,
    priceBDT: 3200,
    priceUSD: 27,
    images: [
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Delicate hand-woven Jamdani floral motifs floating on ivory muslin with flared pleated skirt, smocked back waist for easy fitting, and terracotta ribbon tie.',
    descriptionBn:
      'আইভরি মসলিনের উপর হাতে বোনা জামদানির ফুল। কুঁচি দেওয়া ঘেরযুক্ত ফ্রক এবং সহজে পরার জন্য পেছনে স্মোকড ইলাস্টিক ও ফিতা।',
    features: [
      'Featherlight natural cotton muslin with zero synthetic luster',
      'Soft 100% cotton inner slip prevents irritation',
      'Concealed invisible back zipper with fabric puller',
    ],
    featuresBn: [
      'হালকা ও নরম খাঁটি সুতি জামদানি মসলিন',
      'ভেতরে নরম কটনের আস্তর যা ত্বকে কোনো চুলকানি সৃষ্টি করে না',
      'পেছনে লুকানো মসৃণ চেইন ও ফিতা',
    ],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-12Y'],
    sizeMeasurements: [
      { size: '2-3Y', chest: '22"', length: '20"', waist: '20"' },
      { size: '4-5Y', chest: '24"', length: '23"', waist: '22"' },
      { size: '6-7Y', chest: '26"', length: '26"', waist: '24"' },
      { size: '8-9Y', chest: '28"', length: '29"', waist: '26"' },
      { size: '10-12Y', chest: '30"', length: '32"', waist: '28"' },
    ],
    colors: [
      { name: 'Ivory & Indigo Motifs', nameBn: 'আইভরি ও নীল নকশা', hex: '#F9F6F0' },
      { name: 'Rose Terracotta Motifs', nameBn: 'গোলাপি টেরাকোটা', hex: '#B85324' },
    ],
    inStock: true,
    ageBracket: ['2-7Y'],
  },
  {
    id: 'ind-k-03',
    title: 'Cotton-Linen Casual Kurta Pajama',
    titleBn: 'কটন-লিনেন ক্যাজুয়াল কুর্তা পায়জামা',
    category: 'Kids',
    craftTag: 'Breathable Comfort',
    craftTagBn: 'আরামদায়ক সুতি',
    artisanOrigin: 'Chattogram Port Guild',
    artisanOriginBn: 'চট্টগ্রাম তাঁত সমবায়',
    fabric: '60% Organic Cotton & 40% Natural Flax Linen',
    fabricBn: '৬০% অর্গানিক কটন ও ৪০% ফ্ল্যাক্স লিনেন',
    weaveTimeDays: 3,
    priceBDT: 2200,
    priceUSD: 18,
    images: [
      'https://images.unsplash.com/photo-1471286174890-9c112ffca564?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Airy minimal everyday ethnic wear for boys and girls. Natural river indigo stripes woven directly into the selvedge with side pockets and rolled tab cuffs.',
    descriptionBn:
      'ছেলে ও মেয়ে উভয়ের জন্য উপযোগী আরামদায়ক কুর্তা পায়জামা। ফেব্রিকের পাড়ে প্রাকৃতিক নীলের হালকা স্ট্রাইপ ও রোলড কাফ।',
    features: [
      'Pre-washed linen blend to prevent shrinkage',
      'Machine washable on cold cycle with mild detergent',
      'Includes breathable elasticated ankle-length bottoms',
    ],
    featuresBn: [
      'কাপড় আগেই ধুয়ে নেওয়া যাতে ধোয়ার পর খাটো না হয়',
      'ঠাণ্ডা পানিতে সহজে মেশিনে ধোয়া যায়',
      'সাথে আরামদায়ক সুতি পায়জামা',
    ],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-12Y'],
    sizeMeasurements: [
      { size: '2-3Y', chest: '23"', length: '21"', waist: '20"' },
      { size: '4-5Y', chest: '25"', length: '24"', waist: '22"' },
      { size: '6-7Y', chest: '27"', length: '27"', waist: '24"' },
      { size: '8-9Y', chest: '29"', length: '30"', waist: '26"' },
      { size: '10-12Y', chest: '31"', length: '33"', waist: '28"' },
    ],
    colors: [
      { name: 'Sky Indigo Stripe', nameBn: 'আকাশি নীল স্ট্রাইপ', hex: '#3882B5' },
      { name: 'Raw Ivory Plain', nameBn: 'কাঁচা আইভরি', hex: '#F9F6F0' },
    ],
    inStock: true,
    ageBracket: ['8-15Y'],
  },

  // --- BABY (0-2Y) ---
  {
    id: 'ind-b-01',
    title: '6-Piece Organic Muslin Newborn Welcome Set',
    titleBn: '৬-পিস অর্গানিক মসলিন নবজাতক ওয়েলকাম সেট',
    category: 'Baby',
    craftTag: '100% Organic Muslin',
    craftTagBn: '১০০% অর্গানিক মসলিন',
    artisanOrigin: 'Narayanganj Heritage Muslin Lab',
    artisanOriginBn: 'নারায়ণগঞ্জ হেরিটেজ মসলিন ল্যাব',
    fabric: 'GOTS Certified Ultra-Soft Organic Cotton Muslin',
    fabricBn: 'জিওটিএস সার্টিফায়েড খাঁটি অর্গানিক সুতি মসলিন',
    weaveTimeDays: 5,
    priceBDT: 3600,
    priceUSD: 30,
    isHero: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'The ultimate newborn gift hamper: includes 2 side-tie kimonos, 1 swaddle blanket, 1 hand-embroidered bib, 1 matching beanie cap, and soft scratch mittens packed in an unbleached cotton keepsake bag.',
    descriptionBn:
      'নবজাতকের জন্য সম্পূর্ণ উপহার সেট: ২টি সাইড-টাই কিমোনো জাবলা, ১টি সোয়াডল র‍্যাপ, ১টি হাতে সেলাই করা বিব, ১টি ম্যাচিং টুপি এবং হাতমোজা।',
    features: [
      'Zero harsh chemical dyes, zero formaldehyde, zero bleach',
      'Hand-printed with non-toxic herbal indigo extracts',
      'Packaged in an artisanal golden jute gift case',
    ],
    featuresBn: [
      'কোনোরকম ক্ষতিকর রাসায়নিক বা ব্লিচ মুক্ত',
      'ভেষজ নীল পাতার প্রাকৃতিক নির্যাস দিয়ে হ্যান্ডপ্রিন্ট করা',
      'ঐতিহ্যবাহী পাটের সুদৃশ্য উপহার বাক্সে উপস্থাপিত',
    ],
    sizes: ['0–3M', '3–6M', '6–12M'],
    sizeMeasurements: [
      { size: '0–3M', length: '14"', chest: '18"' },
      { size: '3–6M', length: '16"', chest: '20"' },
      { size: '6–12M', length: '18"', chest: '22"' },
    ],
    colors: [
      { name: 'Herbal Indigo & Raw Cream', nameBn: 'ভেষজ নীল ও ক্রিম', hex: '#0A4269' },
      { name: 'Muted Earth Beige', nameBn: 'মাটি বেইজ', hex: '#756A63' },
    ],
    inStock: true,
    ageBracket: ['0-3M', '3-6M', '6-12M'],
  },
  {
    id: 'ind-b-02',
    title: 'Hand-Embroidered Indigo Baby Romper 2-Pack',
    titleBn: 'হাতে সেলাই করা ইন্ডিগো বেবি রম্পার ২-প্যাক',
    category: 'Baby',
    craftTag: 'Plant Dyes',
    craftTagBn: 'উদ্ভিজ্জ রঙ',
    artisanOrigin: 'Cox’s Bazar Craft Cooperative',
    artisanOriginBn: 'কক্সবাজার কারুশিল্প সমবায়',
    fabric: 'Pre-washed 100% Organic Double-Gauze Cotton',
    fabricBn: '১০০% ডাবল গজ অর্গানিক সুতি কাপড়',
    weaveTimeDays: 4,
    priceBDT: 1850,
    priceUSD: 15,
    images: [
      'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Ultra-breathable summer rompers in soft double-gauze cotton. Nickel-free crotch snap fasteners make diaper changes fast and effortless.',
    descriptionBn:
      'গরমের দিনে শিশুর আরামের জন্য ডাবল গজ সুতি রম্পার। ডায়াপার পরিবর্তনের সুবিধার জন্য নিচে নিকেলমুক্ত স্ন্যাপ বোতাম সংযুক্ত।',
    features: [
      'Cross-back adjustable straps for room to grow',
      'Hand-stitched miniature elephant motif on chest',
      'Gentle elastic thigh openings prevent pinch marks',
    ],
    featuresBn: [
      'শিশুর বৃদ্ধির সাথে সাথে অ্যাডজাস্ট করার উপযোগী স্ট্র্যাপ',
      'বুকে হাতে সুঁই-সুতায় তোলা মিষ্টি হাতির মোটিফ',
      'পায়ে নরম ইলাস্টিক যাতে শিশুর ত্বকে দাগ না পড়ে',
    ],
    sizes: ['0–3M', '3–6M', '6–12M', '12–18M'],
    sizeMeasurements: [
      { size: '0–3M', length: '15"', chest: '18"' },
      { size: '3–6M', length: '17"', chest: '20"' },
      { size: '6–12M', length: '19"', chest: '22"' },
      { size: '12–18M', length: '21"', chest: '24"' },
    ],
    colors: [
      { name: 'Indigo Leaf', nameBn: 'নীল পাতা', hex: '#0A4269' },
      { name: 'Terracotta Clay', nameBn: 'মাটির রঙ', hex: '#B85324' },
    ],
    inStock: true,
    ageBracket: ['0-3M', '3-6M', '6-12M', '12-24M'],
  },
  {
    id: 'ind-b-03',
    title: 'Heirloom Quilted Kantha Baby Blanket',
    titleBn: 'নকশী কাঁথা বেবি কম্বল (ঐতিহ্যবাহী নকশা)',
    category: 'Baby',
    craftTag: 'Hand-Stitched',
    craftTagBn: 'হাতে সেলাই করা',
    artisanOrigin: 'Jessore Nakshi Kantha Guild',
    artisanOriginBn: 'যশোর নকশী কাঁথা সমবায়',
    fabric: '4 Layers of Ultra-Soft Recycled Vintage Muslin',
    fabricBn: '৪ স্তর বিশিষ্ট নরম ও কোমল ভিন্টেজ মসলিন',
    weaveTimeDays: 12,
    priceBDT: 2400,
    priceUSD: 20,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Traditional Bengali baby quilt hand-stitched with love by women artisans in Jessore. Features 4 layers of cloud-soft vintage muslin quilted with concentric rippling ripple stitches.',
    descriptionBn:
      'যশোরের নারী কারিগরদের পরম মমতায় হাতে সেলাই করা ঐতিহ্যবাহী নকশী কাঁথা। চার স্তরের নরম মসলিনে ঢেউ খেলানো সুঁইয়ের কাজ।',
    features: [
      'Dimensions: 38" x 38" (perfect for crib, pram, or tummy time)',
      'Natural temperature-regulating unbleached cotton',
      'Heirloom keepsake crafted to be passed down generations',
    ],
    featuresBn: [
      'পরিমাপ: ৩৮" x ৩৮" (বিছানা ও ট্রাভেলের জন্য উপযুক্ত)',
      'তাপমাত্রা নিয়ন্ত্রণকারী আরামদায়ক সুতি ফেব্রিক',
      'প্রজন্ম থেকে প্রজন্মে যত্ন করে রাখার মতো স্মৃতিস্মারক',
    ],
    sizes: ['One Size (38" x 38")'],
    sizeMeasurements: [
      { size: 'Crib Quilt', length: '38"', chest: '38"' },
    ],
    colors: [
      { name: 'Indigo River Waves', nameBn: 'নীল নদীর ঢেউ', hex: '#0A4269' },
      { name: 'Terracotta Lotus', nameBn: 'পদ্ম টেরাকোটা', hex: '#B85324' },
    ],
    inStock: true,
    ageBracket: ['0-3M', '3-6M', '6-12M', '12-24M'],
  },

  // --- ACCESSORIES ---
  {
    id: 'ind-a-01',
    title: 'Handcrafted Brass Filigree Choker & Earring Set',
    titleBn: 'হাতে গড়া পিতলের ফিলিগ্রি চোকার ও কানের দুল সেট',
    category: 'Accessories',
    craftTag: 'Artisanal Brass',
    craftTagBn: 'হাতে গড়া পিতল',
    artisanOrigin: 'Dhamrai Metal Guild, Dhaka',
    artisanOriginBn: 'ধামরাই মেটাল গিল্ড, ঢাকা',
    fabric: 'Recycled Pure Brass with 22k Gold Antique Matte Dip',
    fabricBn: 'খাঁটি পুনর্ব্যবহারযোগ্য পিতল ও ২২ ক্যারেট ম্যাট গোল্ড ডিপ',
    weaveTimeDays: 6,
    priceBDT: 4500,
    priceUSD: 38,
    isHero: true,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Forged using the 2,000-year-old lost-wax casting technique. Features intricate filigree geometric cutouts inspired by ancient Buddhist terracotta monasteries of Paharpur.',
    descriptionBn:
      'দুই হাজার বছরের প্রাচীন লস্ট-ওয়াক্স পদ্ধতিতে ঢালাই করা পিতলের গহনা। পাহাড়পুরের প্রাচীন বৌদ্ধ বিহারের পোড়ামাটির ফলকের নকশা থেকে অনুপ্রাণিত।',
    features: [
      'Hand-burnished antique finish that will never tarnish',
      'Adjustable pure silk tassel chord to fit all neck sizes',
      'Includes matching dangling filigree stud earrings',
    ],
    featuresBn: [
      'হাতে পালিশ করা টেকসই অ্যান্টিক ফিনিশ',
      'পেছনে রেশমি সুতার অ্যাডজাস্টেবল টার্সেল',
      'সাথে একজোড়া মানানসই ফিলিগ্রি ড্রপ দুল',
    ],
    sizes: ['One Size (Adjustable)'],
    sizeMeasurements: [
      { size: 'Adjustable', length: 'Choker 14"-18"' },
    ],
    colors: [
      { name: 'Antique Burnished Brass', nameBn: 'অ্যান্টিক ব্রাস', hex: '#B85324' },
      { name: 'Indigo Enamel Accent', nameBn: 'নীল এনামেল', hex: '#0A4269' },
    ],
    inStock: true,
  },
  {
    id: 'ind-a-02',
    title: 'Pure Mulberry Silk Handloom Stole / Dupatta',
    titleBn: 'খাঁটি তুত সিল্ক হ্যান্ডলুম স্টোল / ওড়না',
    category: 'Accessories',
    craftTag: 'Mulberry Silk',
    craftTagBn: 'তুত রেশম সিল্ক',
    artisanOrigin: 'Bholahat Silk Belt, Chapainawabganj',
    artisanOriginBn: 'ভোলাহাট সিল্ক বেল্ট, চাঁপাইনবাবগঞ্জ',
    fabric: '100% Mulberry Silk with Fine Hand-Twisted Fringe',
    fabricBn: '১০০% খাঁটি তুত রেশম সিল্ক ও সুতার ঝালর',
    weaveTimeDays: 8,
    priceBDT: 3200,
    priceUSD: 27,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Gauzy and luminous, this versatile unisex drape stole features gradient ombré dyeing from raw sand to midnight Bengal indigo. Edged with hand-knotted fringe.',
    descriptionBn:
      'হালকা ও উজ্জ্বল এই ওড়নাটিতে রয়েছে মাটির রঙ থেকে গাঢ় নীলের অপূর্ব ওমব্রে শেড। পাড়ে হাতে বাঁধা সূক্ষ্ম ঝালরের কাজ।',
    features: [
      'Featherweight 70g total drape weight',
      'Dimensions: 2.2 meters x 0.7 meters',
      'Versatile as a saree dupatta, panjabi shoulder drape, or evening wrap',
    ],
    featuresBn: [
      'ওজনে অত্যন্ত হালকা (মাত্র ৭০ গ্রাম)',
      'পরিমাপ: ২.২ মিটার x ০.৭ মিটার',
      'শাড়ির ওড়না, পাঞ্জাবির সাথে বা যেকোনো পার্টি পোশাকে ব্যবহার্য',
    ],
    sizes: ['Standard (2.2m x 0.7m)'],
    sizeMeasurements: [
      { size: '2.2m Length', length: '86"', chest: '28"' },
    ],
    colors: [
      { name: 'Indigo Ombré', nameBn: 'নীল ওমব্রে', hex: '#0A4269' },
      { name: 'Henna Terracotta Ombré', nameBn: 'টেরাকোটা ওমব্রে', hex: '#B85324' },
    ],
    inStock: true,
  },
  {
    id: 'ind-a-03',
    title: 'Vegetable-Tanned Chattogram Leather Mojari / Sandals',
    titleBn: 'উদ্ভিজ্জ ট্যানড চামড়ার চট্টগ্রাম মোজারি / জুতো',
    category: 'Accessories',
    craftTag: 'Handcrafted Leather',
    craftTagBn: 'হাতে তৈরি চামড়া',
    artisanOrigin: 'Kotwali Leather Artisan Street, Chattogram',
    artisanOriginBn: 'কোতোয়ালি লেদার পট্টি, চট্টগ্রাম',
    fabric: 'Full-Grain Buffalo Leather & Hand-Stitched Cord sole',
    fabricBn: 'খাঁটি মহিষের ফুল-গ্রেইন চামড়া ও হাতে সেলাই করা তলা',
    weaveTimeDays: 5,
    priceBDT: 2800,
    priceUSD: 24,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Handcrafted by generational cobblers in the historic Kotwali leather bazaar of Chattogram. Vegetable-tanned using acacia bark and cold-pressed neem oils for natural water resistance and softness.',
    descriptionBn:
      'চট্টগ্রামের ঐতিহাসিক কোতোয়ালি বাজারের ঐতিহ্যবাহী মুচিদের হাতে তৈরি চামড়ার মোজারি। বাবলা গাছের ছাল ও নিম তেলে প্রাকৃতিকভাবে প্রক্রিয়াজাত।',
    features: [
      'Padded memory foam insole lined with breathable goat leather',
      'Subtle brass stud details and hand-stitched welt cord',
      'Molds to the unique contours of your foot over time',
    ],
    featuresBn: [
      'ভেতরে নরম মেমোরি ফোমের প্যাডিং যা দীর্ঘক্ষণ পরলেও আরাম দেয়',
      'ব্রাস বোতামের কারুকাজ ও মজবুত হাতের সেলাই',
      'ব্যবহারের সাথে সাথে পায়ের গঠনের সাথে চমৎকার মানিয়ে যায়',
    ],
    sizes: ['40 (UK 6)', '41 (UK 7)', '42 (UK 8)', '43 (UK 9)', '44 (UK 10)'],
    sizeMeasurements: [
      { size: '40', length: '10.2"' },
      { size: '41', length: '10.6"' },
      { size: '42', length: '11.0"' },
      { size: '43', length: '11.4"' },
      { size: '44', length: '11.8"' },
    ],
    colors: [
      { name: 'Rustic Terracotta Tan', nameBn: 'রাস্টিক টেরাকোটা ট্যান', hex: '#B85324' },
      { name: 'Deep Indigo Dyed Leather', nameBn: 'নীল চামড়া', hex: '#0A4269' },
    ],
    inStock: true,
  },
]

export const DEMOGRAPHIC_PODS = [
  {
    id: 'women',
    category: 'Women',
    title: 'Women',
    titleBn: 'নারী',
    tagline: 'Silk Sarees & Jamdani',
    taglineBn: 'সিল্ক শাড়ি ও জামদানি',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'men',
    category: 'Men',
    title: 'Men',
    titleBn: 'পুরুষ',
    tagline: 'Raw Silk & Khadi Panjabis',
    taglineBn: 'র সিল্ক ও খাদি পাঞ্জাবি',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'kids',
    category: 'Kids',
    title: 'Kids',
    titleBn: 'শিশু',
    tagline: 'Festive Weaves & Sets',
    taglineBn: 'উৎসবের পোশাক ও সেট',
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'baby',
    category: 'Baby',
    title: 'Baby',
    titleBn: 'নবজাতক',
    tagline: 'Organic Muslin & Kantha',
    taglineBn: 'অর্গানিক মসলিন ও নকশী কাঁথা',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'accessories',
    category: 'Accessories',
    title: 'Accessories',
    titleBn: 'অ্যাক্সেসরিজ',
    tagline: 'Brass Filigree & Leather',
    taglineBn: 'পিতলের গহনা ও চামড়ার মোজারি',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80',
  },
] as const
