import type { LifeWearProduct } from './types'

export const LIFEWEAR_PRODUCTS: LifeWearProduct[] = [
  // ================= MEN =================
  {
    id: 'lw-m-01',
    sku: 'LW-M240-BLK',
    name: 'Heavyweight Supima Crewneck Tee',
    subtitle: '100% Long-Staple American Supima Cotton',
    category: 'men',
    priceBDT: 850,
    priceUSD: 8,
    bundlePriceBDT: 2100,
    bundlePriceUSD: 19,
    bundleQuantity: 3,
    bundleSavingsBDT: 450,
    bundleSavingsUSD: 5,
    gsm: 240,
    spec: '100% Long-Staple Cotton',
    composition: '100% Supima Combed Cotton',
    shrinkage: '< 2.0% wash-tested shrinkage',
    fit: 'Standard Architectural Boxy Fit',
    weave: 'Interlock Dense Knit 240 GSM',
    origin: 'Knitted & Finished in Chattogram Port Zone',
    description:
      'Engineered with extra-long staple Supima cotton fibers that yield unprecedented tensile durability and silky hand-feel. Built with double-needle ribbed crew collar that retains shape through 100+ laundering cycles.',
    features: [
      'Pre-shrunk 240 GSM dense cotton jersey',
      'Reinforced neckband with twin-needle herringbone tape',
      'Tagless heat-transferred technical care specifications',
      'Zero side-twist tubular knitting construction',
    ],
    colors: [
      {
        name: 'Studio White',
        hex: '#FFFFFF',
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Deep Ink Black',
        hex: '#111827',
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Fog Slate Gray',
        hex: '#64748B',
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Signal Navy',
        hex: '#0A2540',
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    defaultImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.9,
    reviewCount: 342,
  },
  {
    id: 'lw-m-02',
    sku: 'LW-M180-OXF',
    name: 'Everyday Tailored Oxford Cloth Shirt',
    subtitle: 'Pre-Shrunk Breathable Weave',
    category: 'men',
    priceBDT: 2400,
    priceUSD: 22,
    gsm: 180,
    spec: 'Pre-Shrunk Breathable Weave',
    composition: '100% Two-Ply Cotton Oxford Weave',
    shrinkage: '< 1.5% post-steamed',
    fit: 'Tailored Utilitarian Straight Silhouette',
    weave: 'Pinpoint Basketweave 180 GSM',
    origin: 'Crafted in Halishahar Mill, Chattogram',
    description:
      'The definitive utilitarian button-up for coastal climate versatility. Engineered with a subtle button-down collar, genuine mother-of-pearl buttons, and moisture-dissipating basketweave yarns.',
    features: [
      'Subtle 2-inch button-down collar with interior interlining',
      'Curved hem designed to stay tucked or fall clean untucked',
      'Clean felled single-needle seams with 18 stitches per inch',
      'Natural garment wash for broken-in softness from day one',
    ],
    colors: [
      {
        name: 'Bleached White',
        hex: '#F8FAFC',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Sky Chambray Blue',
        hex: '#93C5FD',
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Charcoal Pin-Stripe',
        hex: '#334155',
        image: 'https://images.unsplash.com/photo-1620012253295-c15c429f66bf?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    defaultImage: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    reviewCount: 189,
  },
  {
    id: 'lw-m-03',
    sku: 'LW-M280-JOG',
    name: 'All-Day Stretch Chino Utility Joggers',
    subtitle: '4-Way Technical Stretch',
    category: 'men',
    priceBDT: 2800,
    priceUSD: 25,
    gsm: 280,
    spec: '4-Way Technical Stretch',
    composition: '97% Combed Cotton, 3% RoICA Elastane',
    shrinkage: '< 1.8% residual',
    fit: 'Tapered Ergonomic Leg with Gusseted Crotch',
    weave: 'Compact Twill Weave 280 GSM',
    origin: 'Assembled in Agrabad Tech Center, Chattogram',
    description:
      'Combining the sharp appearance of tailored chino trousers with dynamic athletic mobility. Features discreet zippered travel pockets, an internal drawstring, and a 180° diamond seat gusset.',
    features: [
      'Internal stretch drawcord waist with belt loop option',
      'Reinforced welt rear pockets with YKK semi-auto lock zips',
      'Diamond gusseted crotch prevents seam strain during movement',
      'Teflon eco-finish provides soil & light water repellency',
    ],
    colors: [
      {
        name: 'Desert Khaki',
        hex: '#C2B280',
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Tactical Charcoal',
        hex: '#1E293B',
        image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Field Olive',
        hex: '#4D5842',
        image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    defaultImage: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    reviewCount: 215,
  },

  // ================= WOMEN =================
  {
    id: 'lw-w-01',
    sku: 'LW-W190-AIR',
    name: 'Seamless AIR-Touch Supima Fitted Tee',
    subtitle: 'Moisture-Wicking Cotton',
    category: 'women',
    priceBDT: 850,
    priceUSD: 8,
    bundlePriceBDT: 2100,
    bundlePriceUSD: 19,
    bundleQuantity: 3,
    bundleSavingsBDT: 450,
    bundleSavingsUSD: 5,
    gsm: 190,
    spec: 'Moisture-Wicking Cotton',
    composition: '94% Supima Long-Staple Cotton, 6% Micro-Modal',
    shrinkage: '< 2.0% certified',
    fit: 'Precision Contoured Slim Fit',
    weave: 'Circular Fine-Gauge Jersey 190 GSM',
    origin: 'Knit in Nasirabad Technical Facility, Chattogram',
    description:
      'Ultra-fine yarn count creates a featherlight layer that breathes effortlessly in subtropical humidity while opaque enough to wear standalone. Seamless side construction eliminates chafing.',
    features: [
      'Zero side seams with tubular body construction',
      'AIR-Touch moisture dispersion finish',
      'Slightly scooped neckline reinforced with binding',
      'Tagless thermal back print for zero neck irritation',
    ],
    colors: [
      {
        name: 'Studio White',
        hex: '#FFFFFF',
        image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Oatmeal Heather',
        hex: '#E2D9D0',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Minimal Black',
        hex: '#111827',
        image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    defaultImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.9,
    reviewCount: 420,
  },
  {
    id: 'lw-w-02',
    sku: 'LW-W220-LIN',
    name: 'Relaxed High-Waist Linen-Cotton Trousers',
    subtitle: 'Natural Breathable Flax',
    category: 'women',
    priceBDT: 2600,
    priceUSD: 24,
    gsm: 220,
    spec: 'Natural Breathable Flax',
    composition: '55% European Normandy Flax Linen, 45% Long-Staple Cotton',
    shrinkage: '< 2.5% pre-washed',
    fit: 'Fluid Wide-Leg with High Elasticated Back Waist',
    weave: 'Breathable Slub Plain Weave 220 GSM',
    origin: 'Woven & Garment-Dyed in Chattogram',
    description:
      'The supreme warm-weather pant. Woven with authentic flax that softens with every wash while retaining its crisp architectural drape. Equipped with deep utilitarian slash pockets and a clean flat front.',
    features: [
      'Flat front waistband with concealed elasticated rear comfort band',
      'Deep slash front pockets with reinforced bar-tacks',
      'Breathable slub texture promotes active thermal ventilation',
      'Garment washed with non-toxic botanical softeners',
    ],
    colors: [
      {
        name: 'Natural Ecru',
        hex: '#F5F5DC',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Clay Terracotta',
        hex: '#B85324',
        image: 'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Midnight Black',
        hex: '#0E1015',
        image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    defaultImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    reviewCount: 164,
  },
  {
    id: 'lw-w-03',
    sku: 'LW-W110-JKT',
    name: 'Ultra-Light Packable Water-Repellent Jacket',
    subtitle: 'DWR Coated Ripstop',
    category: 'women',
    priceBDT: 3400,
    priceUSD: 30,
    gsm: 110,
    spec: 'DWR Coated Ripstop',
    composition: '100% Recycled Micro-Ripstop Nylon',
    shrinkage: '0.0% hydrophobic stable',
    fit: 'Relaxed Technical Shell with Elastic Hem Cinch',
    weave: 'Diamond Micro-Ripstop 110 GSM',
    origin: 'Bonded in Chattogram EPZ Export Zone',
    description:
      'Weighing a mere 140 grams, this packable technical wind-and-rain barrier self-stows directly into its own chest compartment. Finished with PFC-free durable water repellent for monsoon commutes.',
    features: [
      'Self-stowing design packs down into internal zip pouch',
      'PFC-free bio-based DWR finish sheds light rain and sea spray',
      'Underarm laser-cut ventilation micro-ports prevent clamminess',
      'Reverse-coil YKK zipper with storm flap backing',
    ],
    colors: [
      {
        name: 'Pale Sage Gray',
        hex: '#9BA89E',
        image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Matte Obsidian',
        hex: '#111827',
        image: 'https://images.unsplash.com/photo-1539533018447-63fcce667823?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Signal Blue',
        hex: '#004CE8',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    defaultImage: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1539533018447-63fcce667823?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.9,
    reviewCount: 98,
  },

  // ================= KIDS =================
  {
    id: 'lw-k-01',
    sku: 'LW-K200-TEE',
    name: 'Heavy-Duty Playground Cotton Tee 3-Pack',
    subtitle: 'Reinforced Neckline 200 GSM',
    category: 'kids',
    ageBracket: '2-7Y',
    priceBDT: 1650,
    priceUSD: 15,
    gsm: 200,
    spec: 'Reinforced Neckline 200 GSM',
    composition: '100% Ring-Spun Organic Cotton',
    shrinkage: '< 2.0% durable wash tested',
    fit: 'Active Roomy Toddler Cut',
    weave: 'Heavy-Duty Single Jersey 200 GSM',
    origin: 'Knitted & Finished in Chattogram Port Zone',
    description:
      'Engineered specifically for active toddlers and playground abrasion. Ribbed neck retains elasticity and resists sagging no matter how many times it gets pulled over the head.',
    features: [
      'Pack of 3 coordinating minimalist solid colors',
      'Reinforced high-density neck rib with stretch elastane core',
      'Zero toxic dyes or formaldehyde chemicals (GOTS certified)',
      'Flatlock anti-irritation friction-free seams',
    ],
    colors: [
      {
        name: 'Primary Trio (Navy/White/Oatmeal)',
        hex: '#0A2540',
        image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Earth Trio (Sage/Clay/Ecru)',
        hex: '#708238',
        image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '6-7Y'],
    defaultImage: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    reviewCount: 278,
  },
  {
    id: 'lw-k-02',
    sku: 'LW-K260-TRS',
    name: 'Everyday Elastic-Waist French Terry Shorts',
    subtitle: '100% Organic Terry',
    category: 'kids',
    ageBracket: '2-7Y',
    priceBDT: 1200,
    priceUSD: 11,
    gsm: 260,
    spec: '100% Organic Terry',
    composition: '100% Certified Organic French Terry Cotton',
    shrinkage: '< 2.0% preshrunk',
    fit: 'Relaxed Pull-On Cut with Deep Hand Pockets',
    weave: 'Loopback French Terry 260 GSM',
    origin: 'Knit & Cut in Halishahar, Chattogram',
    description:
      'Soft loopback interior provides active thermal regulation for school and play. Features an encased elastic waistband with a durable cotton herringbone drawcord.',
    features: [
      'Continuous enclosed elastic waistband that stays flat',
      'Genuine functional side pockets for small treasures',
      'Reinforced double-stitch hem prevents fraying',
      'Machine washable at high heat without shrinking',
    ],
    colors: [
      {
        name: 'Heather Gray',
        hex: '#94A3B8',
        image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Maritime Navy',
        hex: '#0A2540',
        image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Washed Olive',
        hex: '#4B5563',
        image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '6-7Y'],
    defaultImage: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    reviewCount: 142,
  },
  {
    id: 'lw-k-03',
    sku: 'LW-K320-HOD',
    name: 'Junior Cotton-Fleece Zip Hoodie',
    subtitle: 'Soft Brushed Interior',
    category: 'kids',
    ageBracket: '8-15Y',
    priceBDT: 2100,
    priceUSD: 19,
    gsm: 320,
    spec: 'Soft Brushed Interior',
    composition: '80% Combed Cotton, 20% Anti-Pill Recycled Poly-Fleece',
    shrinkage: '< 1.8% pre-washed',
    fit: 'Modern Junior Boxy Fit',
    weave: 'Brushed Heavy Fleece 320 GSM',
    origin: 'Crafted in Nasirabad Industrial Zone, Chattogram',
    description:
      'Engineered for junior school commutes and chilly evening air. Features a plush brushed fleece lining, a dual-layer hood with no choking hazard strings, and heavy-gauge YKK metal-tooth zip.',
    features: [
      'Safety-compliant cord-free 3-panel structured hood',
      'Sturdy full-length YKK zipper with chin zipper garage',
      'Ribbed 2x2 cuffs and bottom hem that lock in core warmth',
      'Reinforced kangaroo front hand-warmer pockets',
    ],
    colors: [
      {
        name: 'Cool Fog Gray',
        hex: '#64748B',
        image: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Signal Deep Navy',
        hex: '#0A2540',
        image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Studio Black',
        hex: '#111827',
        image: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['8-10Y', '10-12Y', '12-14Y', '14-15Y'],
    defaultImage: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.9,
    reviewCount: 165,
  },

  // ================= BABY =================
  {
    id: 'lw-b-01',
    sku: 'LW-B180-SNP',
    name: 'Combed Cotton Snap Bodysuit 3-Pack',
    subtitle: 'Oeko-Tex Safe, Nickel-Free Snaps',
    category: 'baby',
    ageBracket: '0-3M',
    priceBDT: 1450,
    priceUSD: 13,
    gsm: 180,
    spec: 'Oeko-Tex Safe, Nickel-Free Snaps',
    composition: '100% Certified Organic Interlock Cotton',
    shrinkage: '< 2.0% sanitized',
    fit: 'Gentle Newborn Ergonomic Fit',
    weave: 'Butter-Soft Interlock 180 GSM',
    origin: 'Sewn in Cleanroom Baby Facility, Chattogram',
    description:
      'Pure organic cotton crafted specifically for sensitive infant skin. Features expandable lap-shoulder necklines that slip downward over the body instead of over the head during diaper mishaps.',
    features: [
      'German Prym nickel-free reinforced snap closures',
      'Envelope fold neckline expands effortlessly over shoulders',
      'Certified Oeko-Tex Standard 100 Class 1 (Baby Safe)',
      '100% natural, unbleached, and chemical-free yarns',
    ],
    colors: [
      {
        name: 'Pure Cloud & Natural Ecru',
        hex: '#F8F9FA',
        image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Muted Sage & Honey',
        hex: '#D1D5DB',
        image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['0-3M', '3-6M'],
    defaultImage: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 5.0,
    reviewCount: 310,
  },
  {
    id: 'lw-b-02',
    sku: 'LW-B210-SLP',
    name: 'Breathable 2-Way Zip Sleepsuit 2-Pack',
    subtitle: '100% Organic Ribbed Cotton',
    category: 'baby',
    ageBracket: '3-6M',
    priceBDT: 1600,
    priceUSD: 14,
    gsm: 210,
    spec: '100% Organic Ribbed Cotton',
    composition: '100% GOTS Certified Rib-Knit Organic Cotton',
    shrinkage: '< 2.0% pre-laundered',
    fit: 'Restful Stretchy Sleep Suit with Fold-Over Cuffs',
    weave: 'Flexible 2x2 Micro-Rib 210 GSM',
    origin: 'Hand-Finished in Chattogram Safe-Knit Lab',
    description:
      'Nighttime diaper changes made frictionless with an inverted two-way safety zipper. Baby stays cozy on top while the bottom unzips in seconds. Includes fold-over mitts on sizes up to 6 months.',
    features: [
      'Dual-direction YKK zipper with top safety zipper tab',
      'Fold-over scratch mitts protect delicate infant faces',
      'Non-slip silicone gripper dots on foot soles',
      'Micro-rib fabric stretches naturally with baby kicks',
    ],
    colors: [
      {
        name: 'Oatmeal Stripe & Slate',
        hex: '#E5E7EB',
        image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Sky Blue & Pure White',
        hex: '#BFDBFE',
        image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['0-3M', '3-6M', '6-12M', '12-24M'],
    defaultImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    reviewCount: 245,
  },
  {
    id: 'lw-b-03',
    sku: 'LW-B240-BIB',
    name: 'Organic Terry Drool Bib & Mittens Set',
    subtitle: 'Hypoallergenic Layer',
    category: 'baby',
    ageBracket: '0-3M',
    priceBDT: 750,
    priceUSD: 7,
    gsm: 240,
    spec: 'Hypoallergenic Layer',
    composition: '100% Organic Cotton Terry with Breathable Waterproof TPU Core',
    shrinkage: '< 1.5% washable',
    fit: 'Adjustable Dual-Snap Contoured Neck',
    weave: 'Absorbent French Loop Terry 240 GSM',
    origin: 'Crafted in Chattogram Clean Mill',
    description:
      'Triple-layer absorbent barrier keeps baby dry from drool rash without soaking clothing. Includes matching ultra-soft no-scratch elasticated infant mittens.',
    features: [
      'Two adjustable snap sizes grow with baby from newborn to 12 months',
      'Ultra-absorbent organic terry loop absorbs 3x its weight in liquid',
      'Concealed waterproof inner membrane stops moisture soak-through',
      'Gentle elastic mitten cuffs that do not leave wrist marks',
    ],
    colors: [
      {
        name: 'Natural Ecru & Sage',
        hex: '#D1FAE5',
        image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['One Size (0-12M)'],
    defaultImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    reviewCount: 112,
  },

  // ================= ACCESSORIES =================
  {
    id: 'lw-a-01',
    sku: 'LW-A500-BPK',
    name: 'Waterproof Cordura Daily Commuter Backpack 22L',
    subtitle: 'YKK Zippers, Laptop Sleeve',
    category: 'accessories',
    priceBDT: 3200,
    priceUSD: 28,
    gsm: 500,
    spec: 'YKK Zippers, Laptop Sleeve',
    composition: '500D Invista Cordura Ballistic Nylon',
    shrinkage: '0.0% rigid composite',
    fit: 'Ergonomic 22L Technical Daypack',
    weave: 'Ballistic Textured Plain Weave 500D',
    origin: 'Constructed in GEC Tech Lab, Chattogram',
    description:
      'A stormproof everyday carry built for monsoon urban commutes. Houses a suspended neoprene 16-inch laptop chamber, water bottle pockets with magnetic drainage, and water-sealed YKK AquaGuard zips.',
    features: [
      '500D ballistic Cordura shell resists rips, scuffs, and abrasions',
      'Suspended padded laptop cradle fits up to 16” MacBook Pro',
      'Waterproof YKK AquaGuard taped seam zips',
      'Breathable 3D mesh back panel with luggage handle pass-through',
    ],
    colors: [
      {
        name: 'Matte Stealth Black',
        hex: '#0E1015',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Urban Charcoal',
        hex: '#334155',
        image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['22L Standard'],
    defaultImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.9,
    reviewCount: 390,
  },
  {
    id: 'lw-a-02',
    sku: 'LW-A100-WOL',
    name: '100% Extra-Fine Merino Wool Beanie',
    subtitle: 'Thermal Regulating',
    category: 'accessories',
    priceBDT: 1100,
    priceUSD: 10,
    gsm: 280,
    spec: 'Thermal Regulating',
    composition: '100% 19.5-Micron Extra-Fine Australian Merino Wool',
    shrinkage: '< 1.0% hand wash tested',
    fit: 'Classic Ribbed Fisherman Fold-Over Cuff',
    weave: 'Fine 7-Gauge Fisherman Rib',
    origin: 'Knitted in Chattogram Hosiery Works',
    description:
      'Naturally odor-resistant, temperature-regulating, and itch-free. Spun from 19.5-micron fine merino wool fibers that insulate when damp and breathe when active.',
    features: [
      'Non-mulesed ethically certified 19.5 micron merino wool',
      'Naturally antibacterial and moisture-wicking',
      'Fold-over cuff allows adjustable crown height',
      'Zero synthetic blend guarantees biodegradable lifecycle',
    ],
    colors: [
      {
        name: 'Deep Navy',
        hex: '#0A2540',
        image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Charcoal Melange',
        hex: '#334155',
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Signal Signal Blue',
        hex: '#004CE8',
        image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['One Size Fits All'],
    defaultImage: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    reviewCount: 210,
  },
  {
    id: 'lw-a-03',
    sku: 'LW-A420-SNK',
    name: 'Minimalist Vulcanized Canvas Everyday Sneakers',
    subtitle: 'Ortho-Cushion Sole',
    category: 'accessories',
    priceBDT: 2500,
    priceUSD: 22,
    gsm: 420,
    spec: 'Ortho-Cushion Sole',
    composition: '14oz Duck Canvas Upper, Natural Rubber Gum Sole',
    shrinkage: '0.0% vulcanized rubberized',
    fit: 'Low-Profile Utilitarian Trainer',
    weave: 'Heavy 14oz Duck Canvas 420 GSM',
    origin: 'Vulcanized in Kalurghat Footwear Works, Chattogram',
    description:
      'Form meets function. Oven-cured vulcanized natural rubber foxing paired with heavy 14oz duck canvas. Features a removable dual-density ergonomic orthotic footbed for 10,000+ daily steps.',
    features: [
      'High-kiln vulcanized natural gum rubber foxing tape',
      'Dual-density Ortho-Cushion memory foam insole',
      'Reinforced nickel eyelets with 100% waxed cotton laces',
      'Padded collar prevents heel chafing during long urban transit',
    ],
    colors: [
      {
        name: 'Studio Raw Chalk',
        hex: '#F8FAFC',
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=80',
      },
      {
        name: 'Minimal Core Black',
        hex: '#111827',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80',
      },
    ],
    sizes: ['EU 39', 'EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'],
    defaultImage: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80',
    ],
    isNew: true,
    rating: 4.8,
    reviewCount: 304,
  },
]
