import type { GlacierProduct } from './types'

export const GLACIER_PRODUCTS: GlacierProduct[] = [
  // ==========================================
  // WOMEN (Sub-Zero Architectural Couture)
  // ==========================================
  {
    id: 'sculptural-hydro-silk-evening-cape-gown',
    title: 'Sculptural Hydro-Silk Evening Cape Gown',
    subtitle: 'Archival Runway Piece • Sub-Zero Hydro Dynamic Weave',
    priceBDT: 18500,
    priceUSD: 160,
    category: 'Women',
    demographic: 'Women',
    spec: 'Sub-Zero Tech-Silk, Net-0',
    thermalRating: 'TOG 2.4 / Sub-Zero Certified',
    thermalGsm: 320,
    techFiberType: 'Hydro-Silk',
    zeroWasteCred: 'Net-0 Hydro Certified',
    stockScarcity: 'Archive 04/50',
    scarcityRemaining: 4,
    scarcityTotal: 50,
    isArchivalDrop: true,
    badge: 'ARCHIVE DROP',
    description:
      'Monolithic draped evening cape gown precision-loomed from hydro-powered tech-silk with sub-zero reflective micro-filaments. Features an architectural high-neck collar that cascadingly unfurls into a crystalline floor-sweeping cape.',
    engineeringDetails: [
      'Sub-Zero Tech-Silk loomed using 100% closed-loop hydro-electricity',
      'Reflective cryo-cyan micro-thread woven into internal warp for ambient luminescence',
      'Laser-fused hemline with zero tension drag across alpine terrain',
      'Net-0 lifecycle certification audited by Maison Chattogram Cryo-Lab',
    ],
    sizes: ['FR 34 (XS)', 'FR 36 (S)', 'FR 38 (M)', 'FR 40 (L)'],
    colors: [
      { name: 'Arctic Obsidian', hex: '#0B0F19', borderHex: '#38BDF8' },
      { name: 'Ice Sheet Silver', hex: '#E0F2FE', borderHex: '#7DD3FC' },
      { name: 'Glacial Cobalt', hex: '#0284C7', borderHex: '#BAE6FD' },
    ],
    images: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'glacial-optical-bias-cut-slit-dress',
    title: 'Glacial Optical Bias-Cut Slit Dress',
    subtitle: 'Kinetic Fluidity • 100% Thermal Memory Crepe',
    priceBDT: 12400,
    priceUSD: 110,
    category: 'Women',
    demographic: 'Women',
    spec: '100% Thermal Memory Crepe',
    thermalRating: 'TOG 1.8 / Ambient Adaptive',
    thermalGsm: 280,
    techFiberType: 'Thermal Crepe',
    zeroWasteCred: 'Closed-Loop Bio-Polymer',
    stockScarcity: 'Archive 08/40',
    scarcityRemaining: 8,
    scarcityTotal: 40,
    isArchivalDrop: true,
    badge: 'LIMITED ALLOCATION',
    description:
      'Engineered on a 45-degree sub-zero bias cut, this optical slit dress reacts to body thermodynamics. The crepe retains structural memory while granting complete liquid movement across architectural silhouettes.',
    engineeringDetails: [
      '100% Thermal Memory Crepe with shape-retention alloy threads',
      'Deep architectural side slit reinforced with laser-welded bonding',
      'Concealed magnetic thermal closures at lateral waist',
      'Ultra-matte finish with anti-static polar sheen',
    ],
    sizes: ['FR 34 (XS)', 'FR 36 (S)', 'FR 38 (M)', 'FR 40 (L)'],
    colors: [
      { name: 'Polar Frost', hex: '#F0F9FF', borderHex: '#38BDF8' },
      { name: 'Deep Glacier', hex: '#082F49', borderHex: '#7DD3FC' },
    ],
    images: [
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'architectural-cocoon-down-coat',
    title: 'Architectural Cocoon Down Coat',
    subtitle: 'Extreme Sub-Zero Barrier • Hydro-Insulated 800-Fill',
    priceBDT: 22000,
    priceUSD: 195,
    category: 'Women',
    demographic: 'Women',
    spec: 'Hydro-Insulated 800-Fill',
    thermalRating: 'TOG 4.8 / -25°C Arctic Grade',
    thermalGsm: 650,
    techFiberType: 'Insulated Down',
    zeroWasteCred: 'RDS Ethically Certified & Recycled Shell',
    stockScarcity: 'Archive 03/30',
    scarcityRemaining: 3,
    scarcityTotal: 30,
    isArchivalDrop: true,
    badge: 'FLAGSHIP ICON',
    description:
      'An avant-garde sculpted cocoon coat constructed with hydro-phobic baffle architecture. Packed with 800-fill responsible down and shielded by a sub-zero membrane that repels freezing rain and coastal gale winds.',
    engineeringDetails: [
      '800-Fill Hydrophobic goose down treated with natural fluorocarbon-free wax',
      'Bonded sonic-welded baffles eliminating thermal cold bridges',
      'Ergonomic architectural funnel neck with internal storm gaiter',
      'Ultra-light Japanese ripstop nylon shell with sub-zero DWR glaze',
    ],
    sizes: ['XS/S', 'M/L', 'XL'],
    colors: [
      { name: 'Abyss Carbon', hex: '#030712', borderHex: '#38BDF8' },
      { name: 'Alpine Chalk', hex: '#F8FAFC', borderHex: '#7DD3FC' },
      { name: 'Cryo Teal', hex: '#0F766E', borderHex: '#2DD4BF' },
    ],
    images: [
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    ],
  },

  // ==========================================
  // MEN (Sub-Zero Tailored High-Tech)
  // ==========================================
  {
    id: 'sub-zero-tailored-tech-wool-overcoat',
    title: 'Sub-Zero Tailored Tech-Wool Overcoat',
    subtitle: 'Monolithic Longline Cut • Hydro-Powered Alpine Wool',
    priceBDT: 19500,
    priceUSD: 170,
    category: 'Men',
    demographic: 'Men',
    spec: 'Hydro-Powered Alpine Wool',
    thermalRating: 'TOG 3.6 / -15°C Certified',
    thermalGsm: 580,
    techFiberType: 'Alpine Wool',
    zeroWasteCred: '100% Regenerative Pasture Sourced',
    stockScarcity: 'Archive 06/45',
    scarcityRemaining: 6,
    scarcityTotal: 45,
    isArchivalDrop: true,
    badge: 'ARCHIVE ICON',
    description:
      'Impeccably tailored monolithic single-breasted overcoat loomed in hydro-powered mills from virgin alpine wool bonded to a microporous wind-barrier membrane. Clean angular shoulders with hidden horn hardware.',
    engineeringDetails: [
      '580 GSM Virgin Alpine Wool with integrated micro-pore membrane',
      'Internal magnetic storm flap and concealed device holster',
      'Laser-beveled lapel edge with hand-finished bar-tack pick stitching',
      'Lined in conductive anti-static silver ion satin',
    ],
    sizes: ['46 (S)', '48 (M)', '50 (L)', '52 (XL)'],
    colors: [
      { name: 'Midnight Abyss', hex: '#020617', borderHex: '#38BDF8' },
      { name: 'Slate Glacier', hex: '#334155', borderHex: '#7DD3FC' },
      { name: 'Polar Ash', hex: '#64748B', borderHex: '#CBD5E1' },
    ],
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'structured-frost-silk-loom-panjabi',
    title: 'Structured Frost Silk-Loom Panjabi',
    subtitle: 'Bengal Heritage x Cryo-Fiber • Metallic Sheen Thread',
    priceBDT: 8200,
    priceUSD: 72,
    category: 'Men',
    demographic: 'Men',
    spec: 'Metallic Sheen Thread',
    thermalRating: 'TOG 1.6 / Climate Regulated',
    thermalGsm: 240,
    techFiberType: 'Hydro-Silk',
    zeroWasteCred: 'Handloom Artisanal Cryo-Warp',
    stockScarcity: 'Archive 11/60',
    scarcityRemaining: 11,
    scarcityTotal: 60,
    isArchivalDrop: true,
    badge: 'HERITAGE REIMAGINED',
    description:
      'Bridging Chattogram handloom legacy with avant-garde glacial optics. High-tensile silk loomed with micro-metallic sheen thread produces a crisp architectural silhouette that catches winter moonlight.',
    engineeringDetails: [
      'Frost-washed silk-cotton blend with sub-zero refractive treatment',
      'Concealed cryo-palladium magnetic placket fasteners',
      'Architectural standing mandarin collar with stiffened fusible inner core',
      'Side gussets with laser-cut cooling ventilation perforations',
    ],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)'],
    colors: [
      { name: 'Frost Platinum', hex: '#F1F5F9', borderHex: '#38BDF8' },
      { name: 'Deep Arctic Teal', hex: '#042F2E', borderHex: '#2DD4BF' },
      { name: 'Glacial Ink', hex: '#0F172A', borderHex: '#7DD3FC' },
    ],
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'precision-cut-monolithic-bonded-blazer',
    title: 'Precision Cut Monolithic Bonded Blazer',
    subtitle: 'Zero-Seam Construction • Laser-Welded Seams',
    priceBDT: 14500,
    priceUSD: 128,
    category: 'Men',
    demographic: 'Men',
    spec: 'Laser-Welded Seams',
    thermalRating: 'TOG 2.2 / Wind-Seal Level 4',
    thermalGsm: 360,
    techFiberType: 'Bonded Tech',
    zeroWasteCred: 'Laser Precision Zero-Scrap Cutting',
    stockScarcity: 'Archive 05/35',
    scarcityRemaining: 5,
    scarcityTotal: 35,
    isArchivalDrop: true,
    badge: 'PRECISION TAILORING',
    description:
      'A triumph of technical tailoring. Traditional stitching is replaced with ultrasonic bonding and laser-welded seams, resulting in a razor-sharp, zero-bulk silhouette that effortlessly resists wet coastal drafts.',
    engineeringDetails: [
      'Ultrasonic laser-welded seams with thermo-polyurethane inner tape',
      '360 GSM Double-faced bonded technical jersey with four-way stretch',
      'Notched modernist lapel with discrete fidlock magnetic chest button',
      'Welded hidden jetted pockets with aqua-guard matte zippers',
    ],
    sizes: ['46 (S)', '48 (M)', '50 (L)', '52 (XL)'],
    colors: [
      { name: 'Deep Arctic Abyss', hex: '#030712', borderHex: '#38BDF8' },
      { name: 'Steel Slate', hex: '#475569', borderHex: '#94A3B8' },
    ],
    images: [
      'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=85',
    ],
  },

  // ==========================================
  // KIDS (Junior Sub-Zero Technical)
  // ==========================================
  {
    id: 'junior-sub-zero-puffer-parka',
    title: 'Junior Sub-Zero Puffer Parka',
    subtitle: 'Childhood Alpine Armour • Lightweight Thermal Barrier',
    priceBDT: 5800,
    priceUSD: 50,
    category: 'Kids',
    demographic: 'Kids',
    spec: 'Lightweight Thermal Barrier',
    thermalRating: 'TOG 4.2 / Extreme Cold Safe',
    thermalGsm: 420,
    techFiberType: 'Insulated Down',
    zeroWasteCred: '100% Recycled Polyester Outer & Eco-Fill',
    stockScarcity: 'Archive 14/70',
    scarcityRemaining: 14,
    scarcityTotal: 70,
    badge: 'JUNIOR ARCTIC',
    description:
      'Engineered specifically for active youngsters navigating cold mornings and school commutes. Ultra-light micro-thermal hollow-fibers maintain core warmth without restricting agility or outdoor exploration.',
    engineeringDetails: [
      'High-loft thermal hollow-core insulation with 0g feather leakage',
      'Reflective 3M Scotchlite ice-cyan sleeve bands for nighttime visibility',
      'Snag-free heavy molded YKK zipper with chin guard soft fleece lining',
      'Tear-resistant ripstop shell with eco DWR stain and moisture shield',
    ],
    sizes: ['4–5 Years', '6–7 Years', '8–9 Years', '10–12 Years'],
    colors: [
      { name: 'Cyan Aurora', hex: '#38BDF8', borderHex: '#0284C7' },
      { name: 'Midnight Polar', hex: '#0F172A', borderHex: '#7DD3FC' },
      { name: 'Glacier Silver', hex: '#CBD5E1', borderHex: '#0EA5E9' },
    ],
    images: [
      'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'frost-proof-technical-utility-joggers',
    title: 'Frost-Proof Technical Utility Joggers',
    subtitle: 'All-Terrain Movement • DWR Coated Stretch',
    priceBDT: 3200,
    priceUSD: 28,
    category: 'Kids',
    demographic: 'Kids',
    spec: 'DWR Coated Stretch',
    thermalRating: 'TOG 2.0 / Wind-Resistant',
    thermalGsm: 300,
    techFiberType: 'Bonded Tech',
    zeroWasteCred: 'OEKO-TEX Class 1 Certified',
    stockScarcity: 'Archive 19/80',
    scarcityRemaining: 19,
    scarcityTotal: 80,
    description:
      'Durable all-weather kids joggers built with double-woven stretch softshell. Waterproof reinforced knee patches withstand playground asphalt while keeping knees warm and protected.',
    engineeringDetails: [
      'Durable Water Repellent (DWR) coating tested for 50+ wash cycles',
      'Abrasion-resistant 500D Cordura knee reinforcement patches',
      'Elasticated drawcord waistband with quick-release toggles',
      'Deep zippered hand pockets to safeguard coins and small treasures',
    ],
    sizes: ['4–5 Years', '6–7 Years', '8–9 Years', '10–12 Years'],
    colors: [
      { name: 'Slate Charcoal', hex: '#1E293B', borderHex: '#38BDF8' },
      { name: 'Arctic Moss', hex: '#134E4A', borderHex: '#5EEAD4' },
    ],
    images: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'alpine-ribbed-merino-wool-knit-pullover',
    title: 'Alpine Ribbed Merino Wool Knit Pullover',
    subtitle: 'Ultra-Soft Warmth • 100% Merino Wool',
    priceBDT: 3600,
    priceUSD: 32,
    category: 'Kids',
    demographic: 'Kids',
    spec: '100% Merino Wool',
    thermalRating: 'TOG 2.8 / Natural Thermoregulation',
    thermalGsm: 340,
    techFiberType: 'Merino',
    zeroWasteCred: '100% Biodegradable Pure Wool',
    stockScarcity: 'Archive 12/55',
    scarcityRemaining: 12,
    scarcityTotal: 55,
    description:
      'Pure 19.5-micron non-itch merino wool spun in an engineered ribbed structure. Regulates body temperature continuously, keeping kids cosy in cold rooms and breathable during active play.',
    engineeringDetails: [
      'Extra-fine 19.5 micron merino fibers spun with smooth combed yarns',
      'Zero synthetic blend—100% natural thermoregulating performance',
      'Pre-washed and shrink-resistant engineered ribbing at cuffs and hem',
      'Hypoallergenic dye certified safe for sensitive young skin',
    ],
    sizes: ['4–5 Years', '6–7 Years', '8–9 Years', '10–12 Years'],
    colors: [
      { name: 'Frost Cream', hex: '#F8FAFC', borderHex: '#7DD3FC' },
      { name: 'Glacier Blue Heather', hex: '#7DD3FC', borderHex: '#0284C7' },
      { name: 'Deep Pine', hex: '#064E3B', borderHex: '#34D399' },
    ],
    images: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?auto=format&fit=crop&w=1200&q=85',
    ],
  },

  // ==========================================
  // BABY (Pure Thermal Protection)
  // ==========================================
  {
    id: 'organic-merino-wool-thermal-receiving-set',
    title: '100% Organic Merino Wool Thermal Receiving Set',
    subtitle: 'Newborn Cradle Cocoon • Hypoallergenic Thermoregulating',
    priceBDT: 4200,
    priceUSD: 36,
    category: 'Baby',
    demographic: 'Baby',
    spec: 'Hypoallergenic Thermoregulating',
    thermalRating: 'TOG 2.5 / Pediatric Safe',
    thermalGsm: 220,
    techFiberType: 'Merino',
    zeroWasteCred: 'GOTS & OEKO-TEX Class 1 Infant Certified',
    stockScarcity: 'Archive 09/50',
    scarcityRemaining: 9,
    scarcityTotal: 50,
    badge: 'NEWBORN ESSENTIAL',
    description:
      'Crafted for precious first moments in cool winter weather. Includes kimono top with fold-over scratch mitts, footed bottoms, and an alpine knot beanie, all loomed from whisper-soft organic merino wool.',
    engineeringDetails: [
      '17.5 micron superfine organic merino—the softest natural fiber available',
      'Flat-locked anti-irritation outer seams protect delicate infant skin',
      'Natural moisture-wicking and antibacterial core prevents rash and dampness',
      'Nickel-free non-magnetic poppers tested to infant safety standards',
    ],
    sizes: ['0–3 Months', '3–6 Months', '6–12 Months'],
    colors: [
      { name: 'Pure Snow Milk', hex: '#FEFBF6', borderHex: '#7DD3FC' },
      { name: 'Ice Mist Blue', hex: '#E0F2FE', borderHex: '#38BDF8' },
    ],
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'insulated-cloud-baby-snowsuit',
    title: 'Insulated Cloud Baby Snowsuit with Detachable Mittens',
    subtitle: 'Deep Winter Pram Stroller Suit • Featherlight Warmth',
    priceBDT: 3800,
    priceUSD: 34,
    category: 'Baby',
    demographic: 'Baby',
    spec: 'Featherlight Warmth',
    thermalRating: 'TOG 3.8 / Wind & Frost Barrier',
    thermalGsm: 360,
    techFiberType: 'Insulated Down',
    zeroWasteCred: 'Recycled Cloud-Microfiber Fill',
    stockScarcity: 'Archive 07/40',
    scarcityRemaining: 7,
    scarcityTotal: 40,
    badge: 'STROLLER ARMOUR',
    description:
      'All-in-one snowsuit with double full-length zippers for instant diaper changes without exposing baby to chilly air. Complete with detachable fleece-lined booties and snap-on mittens.',
    engineeringDetails: [
      'Dual-diagonal full-body zippers from collar to ankles for effortless dressing',
      'Water-repellent peach-skin matte shell blocks damp mist and cold wind',
      'Plush organic cotton velour interior lining against face and neck',
      'Detachable snap-secured booties and fold-over thermal mitten cuffs',
    ],
    sizes: ['0–6 Months', '6–12 Months', '12–18 Months'],
    colors: [
      { name: 'Frost Polar Blue', hex: '#BAE6FD', borderHex: '#0284C7' },
      { name: 'Cloud Pearl', hex: '#F1F5F9', borderHex: '#64748B' },
      { name: 'Arctic Rosewood', hex: '#FFE4E6', borderHex: '#F43F5E' },
    ],
    images: [
      'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'cashmere-touch-muslin-swaddle-2pack',
    title: 'Cashmere-Touch Muslin Swaddle 2-Pack',
    subtitle: 'Breathable Temperature Comfort • Silky Soft Finish',
    priceBDT: 2400,
    priceUSD: 22,
    category: 'Baby',
    demographic: 'Baby',
    spec: 'Silky Soft Finish',
    thermalRating: 'TOG 1.2 / Four-Season Breathable',
    thermalGsm: 180,
    techFiberType: 'Hydro-Silk',
    zeroWasteCred: '100% Closed-Loop Organic Modal & Bamboo',
    stockScarcity: 'Archive 18/90',
    scarcityRemaining: 18,
    scarcityTotal: 90,
    description:
      'Luxurious 120cm x 120cm oversized receiving swaddles woven from sustainable bamboo-modal yarn with a cashmere-like micro-brushed finish. Ensures soothing womb-like pressure without risk of overheating.',
    engineeringDetails: [
      '70% Eco-Bamboo / 30% Organic Cotton open weave for airflow regulation',
      'Micro-brushed hydro-finished texture that softens with every wash',
      'Generous 120x120 cm dimensions for secure swaddling, nursing cover, or stroller shield',
      'AZO-free non-toxic mineral dyes inspired by glacial riverbeds',
    ],
    sizes: ['120cm x 120cm (2-Pack)'],
    colors: [
      { name: 'Glacial Sky & Ice Duo', hex: '#E0F2FE', borderHex: '#38BDF8' },
      { name: 'Natural Sand & Oat Duo', hex: '#F5F5F4', borderHex: '#A8A29E' },
    ],
    images: [
      'https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=85',
    ],
  },

  // ==========================================
  // ACCESSORIES (Glacial Hardware & Optical)
  // ==========================================
  {
    id: 'polarized-optical-shield-eyewear',
    title: 'Polarized Optical Shield Eyewear',
    subtitle: 'Frameless Cryo-Shield • UV400 Glacial Mirror Lens',
    priceBDT: 6500,
    priceUSD: 58,
    category: 'Accessories',
    demographic: 'Accessories',
    spec: 'UV400 Glacial Mirror Lens',
    thermalRating: 'Anti-Fog Cryo-Coating',
    thermalGsm: 120,
    techFiberType: 'Titanium & Optical',
    zeroWasteCred: 'Bio-Acetate & Recycled Polycarbonate',
    stockScarcity: 'Archive 08/45',
    scarcityRemaining: 8,
    scarcityTotal: 45,
    isArchivalDrop: true,
    badge: 'OPTICAL ARCHIVE',
    description:
      'Monolithic cylindrical shield eyewear engineered to eliminate glacial snow-blindness and harsh coastal glare. Features anti-fog hydrophobic coating and titanium micro-temple arms with laser-engraved serials.',
    engineeringDetails: [
      'Toric polycarbonate shield lens with category 3 polarization and UV400 shield',
      'Double-sided anti-reflective cryo-cyan mirror treatment',
      'Ultra-light 18g beta-titanium temples with adjustable silicon nose pads',
      'Packaged in custom milled frosted acrylic hard capsule',
    ],
    sizes: ['One Size (Universal Fit)'],
    colors: [
      { name: 'Electric Ice Cyan Mirror', hex: '#7DD3FC', borderHex: '#0284C7' },
      { name: 'Deep Abyss Chrome', hex: '#1E293B', borderHex: '#94A3B8' },
      { name: 'Glacial Clear Optical', hex: '#F0F9FF', borderHex: '#38BDF8' },
    ],
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'anodized-titanium-carabiner-bangle',
    title: 'Anodized Titanium Carabiner Bangle',
    subtitle: 'Industrial Jewelry • Aerospace-Grade Titanium',
    priceBDT: 4200,
    priceUSD: 38,
    category: 'Accessories',
    demographic: 'Accessories',
    spec: 'Aerospace-Grade Titanium',
    thermalRating: 'Sub-Zero Conductive Neutral',
    thermalGsm: 95,
    techFiberType: 'Titanium & Optical',
    zeroWasteCred: 'CNC Machined from Solid Titanium Billet',
    stockScarcity: 'Archive 15/60',
    scarcityRemaining: 15,
    scarcityTotal: 60,
    description:
      'Precision CNC-milled from aerospace Grade 5 titanium, electro-chemically anodized to emit a crystalline glacial cyan sheen. Features a functional spring-loaded gate mechanism rated for 150kg tensile lock.',
    engineeringDetails: [
      'Grade 5 (Ti-6Al-4V) aerospace titanium—50% lighter than steel and biocompatible',
      'Voltage-controlled anodic oxidation creates permanent iridescent ice-blue coloration',
      'Laser micro-inscribed coordinate stamp: 22.3569° N, 91.7832° E (Chattogram HQ)',
      'Zero skin reactivity; impervious to salt spray, sweat, and sub-zero freeze',
    ],
    sizes: ['Small (16cm)', 'Medium (18cm)', 'Large (20cm)'],
    colors: [
      { name: 'Glacial Electric Blue', hex: '#38BDF8', borderHex: '#0284C7' },
      { name: 'Raw Matte Titanium', hex: '#94A3B8', borderHex: '#E2E8F0' },
      { name: 'PVD Obsidian Black', hex: '#020617', borderHex: '#38BDF8' },
    ],
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1611591475839-444490089851?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=1200&q=85',
    ],
  },
  {
    id: 'bonded-waterproof-arctic-sling-bag',
    title: 'Bonded Waterproof Arctic Sling Bag',
    subtitle: 'Hydro-Fused Storage • Sub-Zero Seamless Construction',
    priceBDT: 4800,
    priceUSD: 42,
    category: 'Accessories',
    demographic: 'Accessories',
    spec: 'Sub-Zero Seamless Construction',
    thermalRating: 'IPX7 Submersible Waterproof',
    thermalGsm: 400,
    techFiberType: 'Bonded Tech',
    zeroWasteCred: 'Upcycled Marine Polymer & Welded TPU',
    stockScarcity: 'Archive 06/35',
    scarcityRemaining: 6,
    scarcityTotal: 35,
    isArchivalDrop: true,
    badge: 'TECHNICAL GEAR',
    description:
      'Seamless RF-welded sling bag made from 420D TPU-laminated ripstop. Features a German Fidlock magnetic V-buckle, water-tight YKK AquaGuard zips, and an insulated interior pocket to prevent device battery drain in freezing temps.',
    engineeringDetails: [
      'Radio-frequency (RF) welded seams granting absolute water and snow immunity',
      'Aerogel-lined phone holster prevents battery voltage drop in sub-zero climates',
      'Fidlock V-buckle magnetic closure enables one-handed release even while wearing ski gloves',
      'Ergonomic quick-adjust ambidextrous strap with breathable EVA back padding',
    ],
    sizes: ['4.5 Liters Volume (Modular Sling)'],
    colors: [
      { name: 'Arctic Abyss Black', hex: '#030712', borderHex: '#38BDF8' },
      { name: 'Frost White Glaze', hex: '#F0F9FF', borderHex: '#0284C7' },
      { name: 'Glacial Slate', hex: '#334155', borderHex: '#7DD3FC' },
    ],
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=1200&q=85',
    ],
  },
]
